"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

type Translations = {
    [key in Language]: {
        [key: string]: string;
    };
};

const translations: Translations = {
    en: {
        dashboard: "Dashboard",
        sales: "Sales",
        rentals: "Rentals",
        staff: "Staff",
        reports: "Reports",
        settings: "Settings",
        welcome: "Welcome back",
        search_placeholder: "Search anything...",
        total_revenue: "Total Revenue",
        active_units: "Active Units",
        pending_invoices: "Pending Invoices",
        revenue_overview: "Revenue Overview",
        recent_activity: "Recent Activity",
        add_unit: "Add Unit",
        create_invoice: "Create Invoice",
        add_employee: "Add Employee",
        units_title: "Property Inventory",
        units_subtitle: "Manage your units and rental assets",
        invoices_title: "Invoices & Billing",
        invoices_subtitle: "Manage transactional history and drafts",
        staff_title: "Staff & HR Operations",
        staff_subtitle: "Manage employees, shifts, and attendance",
        quick_actions: "Quick Actions",
        analysis: "Analysis",
        language: "Language",
        view_details: "View Details",
        price_label: "Price / Month",
        type_label: "Type",
        filter: "Filter",
        apt_1: "Apartment 1 (شقة 1)",
        apt_2: "Apartment 2",
        office_suite: "Office Suite A",
        storage_unit: "Storage Unit 04",
        type_residential: "Residential",
        type_commercial: "Commercial",
        type_industrial: "Industrial",
        export_csv: "Export to CSV",
        upload_doc: "Upload Doc",
        add_photo: "Add Photo",
        assigned: "Assigned",
        team_members: "Team Members",
        latest_transactions: "Latest Transactions",
        branch: "Branch",
        shift: "Shift",
        inventory: "Inventory",
        inventory_subtitle: "Track materials, stock, and cost prices",
        item_name: "Item Name",
        item_code: "Code",
        stock: "Stock",
        cost_price: "Cost Price",
        item_desc: "Description",
        expenses: "Expenses",
        expenses_subtitle: "Fixed costs, utilities, and assets",
        utilities: "Utilities",
        assets: "Assets",
        salary_net: "Net Salary",
        salary_base: "Base Salary",
        penalties: "Penalties",
        vacations: "Vacations",
        installments: "Installments",
        consumer_name: "Consumer Name",
        total_price: "Total Price",
        paid_amount: "Paid Amount",
        remaining: "Remaining",
        projects: "Projects",
        projects_subtitle: "Group and analyze units by construction project",
        add_project: "Add Project",
        project_name: "Project Name",
        total_units: "Total Units",
        project_analytics: "Project Analytics",
        unassigned: "Unassigned",
        select_project: "Select Project",
        price_per_meter: "Price per Meter",
        rooms: "Rooms",
        finished: "Finished",
        unfinished: "Unfinished",
        facilities: "Facilities",
        property_photos: "Property Photos",
        payment_plans: "Payment Plans",
        plan_name: "Plan Name",
        interest_rate: "Interest Rate (%)",
        down_payment: "Down Payment",
        installments_count: "Installments Count",
        overdue: "Overdue",
        collected: "Collected",
        due_this_month: "Due this Month",
        stash: "Stash",
        stash_subtitle: "Manage manual cash inflows and capital deposits",
        add_cash_in: "Add Cash In",
        add_cash_out: "Add Cash Out",
        cash_source: "Source",
        cash_amount: "Amount",
        cash_type: "Type",
        total_receivable: "Total Receivable",
        cheques: "Cheques",
        cheque_management: "Cheque Management",
        inward: "Inward",
        outward: "Outward",
        due_date: "Due Date",
        maturity_date: "Maturity",
        entity: "Entity",
        purpose: "Purpose",
        total_expenses: "Total Expenses",
        net_profit: "Net Profit",
        cash_flow: "Cash Flow",
        financial_forecast: "Financial Forecast",
        operational_costs: "Operational Costs",
        sales_revenue: "Sales Revenue",
        reports_manufacturing: "Manufacturing Reports",
        reports_sms: "SMS Reports",
        reports_points: "Points & Balances",
        reports_memberships: "Memberships Reports",
        reports_workflow: "Workflow Reports",
        reports_timetracking: "Time Tracking",
        reports_activitylog: "Account Activity Log",
        suppliers: "Suppliers",
        supplier_management: "Supplier Directory & Logistics",
        products_sold: "Sold Products",
        contact_info: "Contact Details",
        rating: "Rating",
        supply_chain: "Supply Chain",
        purchases: "Purchases",
        purchase_requests: "Purchase Requests",
        rfqs: "Request for Quotations",
        purchase_quotations: "Purchase Quotations",
        purchase_orders: "Purchase Orders",
        purchase_invoices: "Purchase Invoices",
        purchase_returns: "Purchase Returns",
        debit_notes: "Debit Notes",
        supplier_payments: "Supplier Payments",
        payroll: "Payroll",
        contracts: "Contracts",
        salary_register: "Salary Register",
        salary_slips: "Salary Slips",
        salary_advances: "Salary Advances",
        salary_items: "Salary Items",
        salary_templates: "Salary Templates",
        commissions: "Commissions",
        salesperson: "Salesperson",
        commission_rate: "Commission Rate",
        performance_bonus: "Performance Bonus",
        salary_slips_subtitle: "Detailed monthly breakdowns and payroll receipts",
        search_slips_placeholder: "Search by employee or month...",
        no_salary_slips_found: "No salary slips generated yet. Generate them from the Register.",
        salary_slip_breakdown: "Salary Slip Breakdown",
        payroll_receipt: "Payroll Receipt",
        receipt_id_label: "Receipt ID",
        print_slip_label: "Print Slip",
        employee_information: "Employee Information",
        permanent_staff: "Permanent Staff",
        days_served_label: "Days Served",
        salary_summary: "Salary Summary",
        net_payable_label: "Net Payable",
        payment_breakdown: "Payment Breakdown",
        item_description_label: "Item Description",
        addition_label: "Addition",
        deduction_label: "Deduction",
        transportation_allowance: "Transportation Allowance",
        social_insurance: "Social Insurance",
        vat_label: "VAT (Tax Deducted)",
        loans_advances_repayment: "Loans / Advances Repayment",
        fine_penalties_label: "Fine / Penalties",
        total_net_payable: "TOTAL NET PAYABLE",
        finance_manager_signature: "Finance Manager Signature",
        certified_digital_payroll: "Certified Digital Payroll Document",
        salary_advances_subtitle: "Manage employee loan requests and repayment schedules",
        search_advances_placeholder: "Search advances...",
        request_advance: "Request Advance",
        repayment_starts: "Repayment Starts",
        syncing_advances: "Syncing advance records...",
        no_advance_requests_found: "No advance requests found.",
        amount_greater_than_zero_error: "Amount must be greater than 0",
        save_advance_failed: "Failed to save advance request.",
        update_status_failed: "Failed to update status.",
        edit_advance_record: "Edit Advance Record",
        new_advance_request: "New Advance Request",
        advance_amount_egp: "Advance Amount (EGP)",
        purpose_of_advance_placeholder: "Purpose of this advance...",
        advance_hint_text: "This will update the salary register and approve the loan. Payments will be deducted from the employee's salary starting from the repayment start date.",
        egp: "EGP",
        close_label: "Close",
        na_label: "N/A",
        confirm_delete_record: "Delete record?",
        paid_status: "Paid",
        approved: "Approved",
        rejected: "Rejected",
        enter_item_name_error: "Please enter an item name",
        save_item_failed: "Failed to save item.",
        search_items_placeholder: "Search items...",
        no_salary_items_found: "No salary items defined. Create your first addition or deduction.",
        confirm_delete_item: "Delete item?",
        addition: "Addition",
        deduction: "Deduction",
        recurring: "Recurring",
        edit_salary_item: "Edit Salary Item",
        create_salary_item: "Create Salary Item",
        item_name_payroll_placeholder: "e.g., Health Insurance, Transportation, VAT 14%",
        value_type_label: "Value Type",
        fixed_amount_egp: "Fixed Amount (EGP)",
        percentage_label: "Percentage (%)",
        recurring_every_month: "Recurring every month",
        salary_templates_subtitle: "Exportable monthly payroll sheets and reports",
        total_base_payroll: "Total Base Payroll",
        monthly_payroll_sheet: "Monthly Payroll Sheet",
        organization_payroll_report: "Organization Payroll Report",
        filter_by_name_placeholder: "Filter by name...",
        generating_report: "Generating report...",
        no_payroll_data_month: "No payroll data for this month.",
        unknown: "Unknown",
        totals: "Totals",
        prepared_by: "Prepared By",
        approved_by: "Approved By",
        days: "Days",
        staff_label: "Staff",
        save_failed: "Failed to save data.",
        delete_confirm: "Are you sure you want to delete this?",
        priority: "Priority",
        low: "Low",
        medium: "Medium",
        high: "High",
        items_count: "items",
        unique_items: "unique items",
        requested_items: "Requested Items",
        add_item: "Add Item",
        qty: "Qty",
        estimated_price: "Est. Price",
        loading_data: "Loading data...",
        no_data: "No data available.",

        // Purchasing & Suppliers Extension
        purchase_requests_title: "Purchase Requests",
        purchase_requests_subtitle: "Draft and submit requests for materials, office supplies, or services.",
        new_request: "New Request",
        active_requests: "Active Requests",
        request_title: "Request Title",
        loading_requests: "Loading requests...",
        no_purchase_requests_yet: "No purchase requests yet.",
        no_description: "No description",
        purchase_orders_title: "Purchase Orders",
        purchase_orders_subtitle: "Manage supplier orders, inventory requests, and expenses",
        create_order: "Create Order",
        total_sourced_value: "Total Sourced Value",
        lifetime_orders_desc: "Lifetime tracked purchase orders",
        order_history: "Order History",
        search_orders: "Search orders...",
        order_ref: "Order Ref",
        order_number_label: "Order Number",
        date_logged: "Date Logged",
        classification: "Classification",
        order_details: "Order Details",
        order_reference: "Order Reference",
        link_approved_quotation: "Link Approved Quotation",
        independent_order: "Independent Order",
        order_classification: "Order Classification",
        standard_items: "Standard Items",
        inventory_stock: "Inventory Stock",
        standard_quotation: "Standard Quotation",
        bulk_wholesale: "Bulk / Wholesale",
        urgent_request: "Urgent Request",
        financial_status: "Financial & Status",
        total_expected_amount: "Total Expected Amount (EGP)",
        current_status: "Current Status",
        sent_processing: "Sent / Processing",
        completed_paid: "Completed / Paid",
        documentation_notes: "Documentation & Notes",
        invoice_receipt_url: "Paste invoice/receipt URL link...",
        additional_details: "Additional details...",
        auto_expense_hint: "★ Marking this completed will auto-log it to Expenses.",
        purchase_quotations_title: "Purchase Quotations",
        purchase_quotations_subtitle: "Review and approve final supplier bids.",
        add_quote: "Add Quote",
        winning_bid: "Winning Bid",
        bid_amount: "Total Bid Amount",
        approve_quote_confirm: "Approve this quotation? This will reject others for the same RFQ.",
        quote_approved_success: "Quotation approved successfully!",
        no_purchase_quotations_found: "No quotations found",
        enter_supplier_quotes_desc: "Enter supplier quotes for your RFQs to start the comparison process.",
        enter_supplier_quotation: "Enter Supplier Quotation",
        linked_rfq: "Linked RFQ",
        select_supplier: "Select Supplier",
        select_supplier_placeholder: "Select supplier...",
        independent_quote: "Independent Quote",
        quote_date: "Quote Date",
        rfqs_title: "Request for Quotations",
        rfqs_subtitle: "Create and manage RFQs to compare multiple suppliers.",
        new_rfq: "New RFQ",
        active_rfqs: "Active RFQs",
        rfq_title: "RFQ Title",
        rfq_details: "RFQ Details",
        closing_date: "Closing Date",
        vendor_selection: "Vendor Selection",
        no_rfqs_found: "No RFQs found",
        create_rfq_desc: "Create a request to get competitive bids from vendors.",
        new_rfq_modal_title: "Create New RFQ",
        rfq_reference: "RFQ Reference",
        view_quotes: "View Quotes",
        approve: "Approve",
        reject: "Reject",
        general_quote: "General Quote",
        rfq_description_desc: "Compare prices from multiple suppliers for your purchase requests.",
        no_active_rfqs: "No active RFQs",
        active_rfqs_desc: "Create a Request for Quotation to start receiving and comparing supplier bids.",
        create_rfq_modal_title: "Create Request for Quotation",
        rfq_title_subject: "RFQ Title / Subject",
        rfq_title_placeholder: "e.g. Bulk Cement Purchase Q2",
        linked_purchase_request: "Linked Purchase Request (Optional)",
        independent_rfq: "Independent RFQ",
        deadline_for_bids: "Deadline for Bids",
        select_suppliers_to_invite: "Select Suppliers to Invite",
        no_suppliers_in_directory: "No suppliers found in directory.",
        suppliers_count: "Suppliers",
        purchase_invoices_title: "Purchase Invoices",
        purchase_invoices_subtitle: "Manage bills and payments for your purchase orders.",
        add_invoice: "Add Invoice",
        invoice_no: "Invoice No",
        po_ref: "PO Ref",
        no_purchase_invoices_yet: "No purchase invoices yet.",
        loading_invoices: "Loading invoices...",
        add_purchase_invoice: "Add Purchase Invoice",
        linked_purchase_order: "Linked Purchase Order",
        select_po_placeholder: "Select PO...",
        invoice_number_label: "Invoice Number",
        invoice_date: "Invoice Date",
        partially_paid: "Partially Paid",
        // overdue removed (duplicate)
        unpaid: "Unpaid",
        purchase_returns_title: "Purchase Returns",
        purchase_returns_subtitle: "Handle item returns and supplier refunds.",
        log_return: "Log Return",
        return_history: "Return History",
        return_date: "Return Date",
        refund_amount: "Refund Amount",
        no_purchase_returns_logged: "No purchase returns logged.",
        loading_returns: "Loading returns...",
        log_purchase_return: "Log Purchase Return",
        linked_invoice_optional: "Linked Invoice (Optional)",
        independent_return: "Independent Return",
        reason_for_return: "Reason for Return",
        purchase_return_logged_alert: "Purchase Return logged. Inventory adjustments should be verified manually.",
        supplier_directory_title: "Supplier Directory",
        supplier_directory_subtitle: "Manage your logistics partners and product sources.",
        add_supplier: "Add Supplier",
        logistics_partners: "Logistics Partners",
        search_suppliers: "Search suppliers...",
        supplier_name_label: "Supplier Name",
        contact_person: "Contact Person",
        linked_products: "Linked Products",
        no_suppliers_found_desc: "No suppliers found. Add your first logistics partner.",
        edit_supplier: "Edit Supplier",
        add_new_supplier: "Add New Supplier",
        supplier_company_name: "Supplier Company Name",
        supplier_name_placeholder: "e.g. Al-Futtaim Logistics",
        full_name_placeholder: "Full Name",
        phone_number_label: "Phone Number",
        email_address_label: "Email Address",
        address_warehouse: "Address / Warehouse",
        no_address: "No Address",
        no_linked_products: "No linked products",
        supplier_payments_title: "Supplier Payments",
        supplier_payments_subtitle: "Settle invoices and track outgoing logistics funds.",
        process_payment: "Process Payment",
        payment_history: "Payment History",
        reference: "Reference",
        method: "Method",
        no_payment_records_found: "No payment records found.",
        loading_payments: "Loading payments...",
        process_supplier_payment: "Process Supplier Payment",
        select_logistics_partner: "Select a logistics partner...",
        payment_amount_egp: "Payment Amount (EGP)",
        payment_method: "Payment Method",
        bank_transfer: "Bank Transfer",
        cash: "Cash",
        cheque: "Cheque",
        stash_funds: "Stash Funds",
        reference_receipt_no: "Reference / Receipt No.",
        payment_description: "Payment Description",
        delete_payment_confirm: "Delete this payment record? Note: Linked expense will persist.",
        debit_notes_title: "Debit Notes & Installments",
        debit_notes_subtitle: "Manage long-term supplier liabilities and payment schedules.",
        new_debit_note: "New Debit Note",
        total_liability: "Total Liability",
        active_status: "Active",
        payment_progress: "Payment Progress",
        no_active_debit_notes: "No active Debit Notes",
        no_debit_notes_desc: "You haven't added any supplier liabilities or payment schedules yet.",
        new_supplier_liability: "New Supplier Liability (Debit Note)",
        number_of_payments: "Number of Payments",
        first_payment_date: "First Payment Date",
        liability_description: "Liability Description",
        liability_description_placeholder: "E.g. Purchase of 100 units on credit...",
        debit_note_created_alert: "Debit Note created. Future installments have been scheduled.",
        no_description_provided: "No description provided",
        installments_sync_msg: "Installments will appear here once synchronized.",
        // Sidebar & Navigation
        task_board: "Task Board",
        staff_modules: "Staff Modules",
        core_modules: "Core Modules",
        human_resources: "Human Resources",
        purchasing_logistics: "Purchasing & Logistics",
        financials_reports: "Financials & Reports",
        payroll_engine: "Payroll engine",
        payroll_engine_desc: "Manage employee compensation, contracts, and registers.",
        review_requests: "Review Requests",
        loans_dashboard: "Loans Dashboard",
        clients: "Clients",
        purchasing_cycle: "Purchasing Cycle",
        purchasing_cycle_desc: "Manage procurement, orders, and purchase returns.",
        suppliers_logistics: "Suppliers & Logistics",
        suppliers_logistics_desc: "Manage vendor relationships, payments, and directories.",
        employees_directory: "Employees Directory",
        cashflow_forecast: "Cashflow Forecast",
        staff_member: "Staff Member",
        plan_platinum: "Platinum",
        plan_label: "Plan",
        sales_invoices: "Sales Invoices",
        client_quotations: "Client Quotations",

        // Dashboard
        launch_wizard: "Launch Wizard",
        interactive_setup_wizard: "Interactive Setup Wizard",
        team_members_kpi: "Team Members",
        listed_services: "Listed Services",
        active_loans_debt: "Active Loans Debt",
        active_loans_debt_desc: "Total active loan debt currently payable",
        loans_manage_desc: "Manage payment status, balances, and track linking through the Treasury (Stash) module.",
        service_listed: "Service listed",
        team_member_added: "Team Member added",
        no_activity: "No recent activity detected.",
        wizard_desc: "New to the system? Launch our interactive step-by-step pipeline to guide you through creating your team, setting up your first project, and configuring your finances.",

        // Inventory
        add_material: "Add Material",
        material_stock: "Material Stock",
        actions: "Actions",
        in_stock: "In Stock",
        low_stock: "Low Stock",
        out_of_stock: "Out of Stock",
        linked_project_label: "Linked Project",
        none_general_material: "None / General Material",
        add_inventory_item: "Add Inventory Item",
        item_name_placeholder: "e.g. Cement",
        item_code_placeholder: "e.g. MAT-001",
        syncing_inventory: "Syncing inventory...",

        // Expenses
        assigned_service_item: "Assigned Service / Item",
        general_service_cost: "General Service Cost",
        general: "General",
        fixed: "Fixed",
        variable: "Variable",
        asset: "Asset",
        receipt_photo_optional: "Receipt Photo (Optional)",
        file_attached: "File Attached",
        provider: "Provider",
        select_provider: "Select Provider",
        expense_description_placeholder: "Enter details...",
        select_category: "Select Category",
        variable_costs_desc: "Variable Costs",
        operating_expenses_desc: "Operating Expenses",

        // Staff
        employee: "Employee",
        add_penalty: "Add Penalty",
        add_vacation: "Add Vacation",
        pay_salary: "Pay Salary",
        full_time: "Full Time",
        daily: "Daily",
        day_label: "day",
        mo_label: "mo",
        days_unit: "Days",
        employment_type: "Employment Type",
        role_label: "Role",
        daily_rate_label: "Daily Rate",
        team_members_payroll: "Team Members & Payroll",
        select_avatar: "Select Avatar (Funny / Professional)",
        hire_date_label: "Start Date / Hire Date",
        employee_saved_success: "Employee saved successfully.",
        add_staff_failed: "Failed to add staff member: ",
        pay_salary_success: "Salary Payment generated successfully in Expenses.",
        pay_salary_failed: "Failed to pay salary.",
        penalty_added_success: "Penalty added successfully.",
        penalty_failed: "Failed to add penalty.",
        vacation_recorded_success: "Vacation recorded successfully.",
        vacation_recorded_failed: "Failed to record vacation.",
        process_salary: "Process Salary",
        employment_type_label: "Employment Type",
        rate_label: "Rate",
        final_salary_invoice: "Final Salary Invoice",
        penalty_amount_egp: "Penalty Amount (EGP)",
        reason_label: "Reason",
        penalty_hint: "This amount will be automatically subtracted from the next salary payment.",
        record_vacation: "Record Vacation",
        start_date_label: "Start Date",
        end_date_label: "End Date",
        total_vacation_days: "Total Vacation Days",
        reason_notes: "Reason / Notes",
        vacation_placeholder: "e.g. Annual Leave, Family Event",
        penalty_placeholder: "e.g. Late for work, Misconduct",
        days_worked: "Days Worked",
        salary_register_title: "Salary Register",
        salary_register_subtitle: "Track payments and manage balances",
        search_staff_month: "Search employee or month...",
        period_label: "Period",
        record_payment: "Record Payment",
        generate_update_slip: "Generate/Update Slip",
        syncing_register: "Syncing register...",
        no_salary_records_found: "No salary records found matching your search.",
        total_outstanding: "Total Outstanding",
        full_amount: "Full Amount",
        payment_process_hint: "This will update the salary register and create a corresponding record in the Expenses module.",
        partial_payment_note: " This will be recorded as a PARTIAL payment.",
        full_settlement_note: " This will be recorded as a FULL settlement.",
        employee_contracts_title: "Employee Contracts",
        employee_contracts_subtitle: "Formalize tasks, salary terms and service management",
        search_contracts: "Search contracts...",
        create_contract: "Create Contract",
        no_contracts_found: "No contracts found. Start by creating one.",
        unknown_staff: "Unknown Staff",
        managing_label: "Managing:",
        base_label: "Base:",
        inc_label: "Inc.",
        starts_label: "Starts:",
        ends_label: "Ends:",
        new_employment_contract: "New Employment Contract",
        select_staff: "Select Staff",
        primary_tasks: "Primary Tasks / Responsibilities",
        tasks_placeholder: "Core duties and expected deliverables...",
        base_salary_egp: "Base Monthly Salary (EGP)",
        yearly_increase_label: "Yearly Increase (%)",
        managed_service_optional: "Managed Service (Optional)",
        no_service_responsibility: "No Service Responsibility",
        end_date_optional: "End Date (Optional)",
        contract_saved_success: "Contract saved successfully.",
        contract_save_failed: "Failed to save contract.",
        contractor: "Contractor",
        salary_paid_success_expense: "Payment processed and recorded in expenses.",
        salary_payment_error: "Payment error:",
        salary_payment_failed: "Failed to process payment.",
        no_active_contract_alert: "No active contract found for this employee. Please create a contract first.",
        salary_slip_generated_success: "Salary slip generated and net pay updated successfully!",
        salary_slip_generate_failed: "Failed to generate salary slip.",

        // Settings Extension
        configure_erp_desc: "Configure your ERP environment and preferences",
        language_interface_desc: "Change the interface language (Bilingual EN/AR)",
        english_us: "English (US)",
        arabic_eg: "العربية (Arabic)",
        user_profile: "User Profile",
        manage_profile_desc: "Manage your personal information and avatar",
        company_name_dashboard: "Company Name (Dashboard Title)",
        company_name_placeholder: "e.g. My Business Ltd",
        profile_picture_url: "Profile Picture URL",
        profile_picture_desc: "Provide a valid image URL for your avatar.",
        save_profile: "Save Profile",
        branches_storage_title: "Company Branches & Storage",
        branches_storage_desc: "Manage physical locations for expenses and invoices",
        add_branch: "Add Branch",
        loading_branches: "Loading branches...",
        no_branches_defined: "No branches or storage locations defined yet.",
        edit_branch: "Edit Branch",
        no_address_provided: "No address provided",
        subscription_tier_title: "Subscription Tier",
        subscription_tier_desc: "Unlock premium features and increase your user limits.",
        silver_plan: "Silver Plan",
        gold_plan: "Gold Plan",
        platinum_plan: "Platinum Plan",
        per_mo: "EGP /mo",
        or_per_yr: "or 30,000 EGP /yr",
        current_plan: "Current Plan",
        included: "Included",
        select_silver: "Select Silver",
        upgrade_to_gold: "Upgrade to Gold",
        upgrade_to_platinum: "Upgrade to Platinum",
        danger_zone: "Danger Zone",
        destructive_actions_desc: "Destructive actions and account logouts",
        sign_out: "Sign Out",
        sign_out_desc: "End your current session securely.",
        delete_account: "Delete Account",
        delete_account_desc: "Permanently remove your user. This cannot be undone.",
        delete_confirm_placeholder: "Type DELETE",
        delete_button: "Delete",
        branch_location_name: "Branch / Location Name",
        branch_location_placeholder: "e.g. Headquarters, Downtown Office...",
        address_details: "Address / Details",
        address_placeholder: "Physical address or contact info...",

        // Expenses Extension
        rent_invoice: "Rent Invoice",
        maintenance_invoice: "Maintenance Invoice",
        internet_invoice: "Internet Invoice",
        electricity_invoice: "Electricity Invoice",
        water_invoice: "Water Invoice",
        phone_mobile_invoice: "Phone / Mobile Invoice",
        tax: "Tax",
        insurance: "Insurance",
        government_utilities: "Government utilities (الحي)",
        office_supplies: "Office Supplies",
        custom_expense_placeholder: "Enter custom expense category...",
        internet_provider: "Internet Provider",
        we_telecom_egypt: "WE (Telecom Egypt)",
        vodafone_egypt: "Vodafone Egypt",
        orange_egypt: "Orange Egypt",
        etisalat_misr: "Etisalat Misr",
        nour_adsl: "Nour ADSL",

        // Staff Extension
        consultant: "Consultant",
        active: "Active",
        edit_employee: "Edit Employee",
        employee_name: "Employee Name",
        email_placeholder: "email@company.com",
        role_placeholder: "e.g. Sales Manager",
        part_time: "Part Time",
        temporary: "Temporary",

        // Quotations
        new_quotation: "New Quotation",
        quotations_subtitle: "Manage proposals and recurring service contracts",
        search_quotes: "Search quotes...",
        proposal: "Proposal",
        client_account: "Client / Account",
        valid_until: "Valid Until",
        syncing_proposals: "Syncing proposals...",
        no_client_quotations_found: "No quotations found. Start by creating one!",
        mark_accepted: "Mark Accepted",
        one_time: "One-time",
        proposal_name: "Title / Proposal Name",
        select_client: "Select Client",
        choose_client: "-- Choose Client --",
        related_project: "Related Project / Account",
        optional_account: "-- Optional Account --",
        quoted_amount: "Quoted Amount",
        recurring_billing: "Recurring Billing",
        cycle: "Cycle",
        terms: "Terms",
        brief_description: "Brief Description / Scope",
        scope_placeholder: "Outline the services included...",
        new_client_quotation: "New Client Quotation",

        // Loans
        loan_management: "Loan Management",
        loans_subtitle: "Track internal & external loans and advances",
        issue_loan: "Issue Loan",
        outstanding_balance: "Outstanding Balance",
        active_accounts: "Active Accounts",
        loan_accounts: "Loan Accounts",
        search_loans: "Search loans...",
        borrower: "Borrower",
        principal: "Principal",
        remaining_balance: "Remaining Balance",
        loading_loans: "Loading loans data...",
        paid_off: "Paid Off",
        defaulted: "Defaulted",
        update_loan_account: "Update Loan Account",
        issue_new_loan: "Issue New Loan",
        borrower_name: "Borrower Name",
        principal_amount: "Principal Amount",
        term_limit: "Term limit (Months)",
        loan_progress: "Loan Progress",
        total_paid_back: "Total Amount Paid Back",
        linking_stash_hint: "Update this when linking Stash inflows to this loan account.",

        // Settings
        personal_name: "Personal Name",
        company_name: "Company Name",
        update_profile: "Update Profile",
        update_company: "Update Company",
        profile_picture: "Profile Picture",
        organization_logo: "Organization Logo",
        confirm_delete_supplier: "Delete supplier?",
        add_inventory_item_failed: "Failed to add inventory item.",
        salary_payment_desc: "Salary Payment for",
        pmt_label: "PMT",
        debit_note_prefix: "Debit Note #",
        days_worked_colon: "Days Worked:",
        supplier_payment_desc_prefix: "Supplier Payment:",
        confirm_delete_material: "Delete material?",

        rtl: "false"
    },
    ar: {
        dashboard: "لوحة التحكم",
        sales: "المبيعات",
        rentals: "الإيجارات",
        staff: "الموظفين",
        reports: "التقارير",
        settings: "الإعدادات",
        welcome: "مرحباً بك مجدداً",
        search_placeholder: "ابحث عن أي شيء...",
        total_revenue: "إجمالي الإيرادات",
        active_units: "الوحدات النشطة",
        pending_invoices: "الفواتير المعلقة",
        revenue_overview: "نظرة عامة على الإيرادات",
        recent_activity: "النشاط الأخير",
        add_unit: "إضافة وحدة",
        create_invoice: "إنشاء فاتورة",
        add_employee: "إضافة موظف",
        units_title: "مخزون العقارات",
        units_subtitle: "إدارة الوحدات والأصول الإيجارية",
        invoices_title: "الفواتير والفوترة",
        invoices_subtitle: "إدارة السجل المعاملاتي والمسودات",
        staff_title: "الموظفين وعمليات الموارد البشرية",
        staff_subtitle: "إدارة الموظفين، المناوبات، والحضور",
        quick_actions: "إجراءات سريعة",
        analysis: "التحليل",
        language: "اللغة",
        view_details: "عرض التفاصيل",
        price_label: "السعر / شهر",
        type_label: "النوع",
        filter: "تصفية",
        apt_1: "شقة 1 (Apartment 1)",
        apt_2: "شقة 2",
        office_suite: "جناح مكاتب أ",
        storage_unit: "وحدة تخزين 04",
        type_residential: "سكني",
        type_commercial: "تجاري",
        type_industrial: "صناعي",
        export_csv: "تصدير إلى CSV",
        upload_doc: "رفع مستند",
        add_photo: "إضافة صورة",
        assigned: "تم تعيينهم",
        team_members: "أعضاء الفريق",
        latest_transactions: "أحدث المعاملات",
        branch: "الفرع",
        shift: "المناوبة",
        inventory: "المخزون",
        inventory_subtitle: "تتبع المواد، المخزون، وأسعار التكلفة",
        item_name: "اسم الصنف",
        item_code: "الكود",
        stock: "المخزون",
        cost_price: "سعر التكلفة",
        item_desc: "الوصف",
        expenses: "المصاريف",
        expenses_subtitle: "التكاليف الثابتة، المرافق، والأصول",
        utilities: "المرافق",
        assets: "الأصول",
        salary_net: "صافي الراتب",
        salary_base: "الراتب الأساسي",
        penalties: "الجزاءات",
        vacations: "الإجازات",
        installments: "الأقساط",
        consumer_name: "اسم المستهلك",
        total_price: "السعر الإجمالي",
        paid_amount: "المبلغ المدفوع",
        remaining: "المتبقي",
        projects: "المشاريع",
        projects_subtitle: "تجميع وتحليل الوحدات حسب مشروع البناء",
        add_project: "إضافة مشروع",
        project_name: "اسم المشروع",
        total_units: "إجمالي الوحدات",
        project_analytics: "تحليلات المشروع",
        unassigned: "غير محدد",
        select_project: "اختر المشروع",
        price_per_meter: "سعر المتر",
        rooms: "الغرف",
        finished: "مشطب",
        unfinished: "بدون تشطيب",
        facilities: "المرافق",
        property_photos: "صور العقار",
        payment_plans: "خطط الدفع",
        plan_name: "اسم الخطة",
        interest_rate: "نسبة الفائدة (%)",
        down_payment: "الدفعة المقدمة",
        installments_count: "عدد الأقساط",
        overdue: "متأخر",
        collected: "محصل",
        due_this_month: "مستحق هذا الشهر",
        stash: "الخزنة",
        stash_subtitle: "إدارة التدفقات النقدية اليدوية وتدفقات رأس المال",
        add_cash_in: "إضافة نقد وارد",
        add_cash_out: "إضافة نقد صادر",
        cash_source: "المصدر",
        cash_amount: "المبلغ",
        cash_type: "النوع",
        total_receivable: "إجمالي المستحقات",
        cheques: "الشيكات",
        cheque_management: "إدارة الشيكات",
        inward: "وارد",
        outward: "صادر",
        due_date: "تاريخ الاستحقاق",
        maturity_date: "الاستحقاق",
        entity: "الجهة",
        purpose: "الغرض",
        total_expenses: "إجمالي المصروفات",
        net_profit: "صافي الربح",
        cash_flow: "التدفق النقدي",
        financial_forecast: "التوقعات المالية",
        operational_costs: "التكاليف التشغيلية",
        sales_revenue: "إيرادات المبيعات",
        reports_manufacturing: "تقارير التصنيع",
        reports_sms: "تقارير الـ SMS",
        reports_points: "تقارير النقاط و الأرصدة",
        reports_memberships: "تقارير العضويات",
        reports_workflow: "تقارير دورة العمل",
        reports_timetracking: "تقارير تتبع الوقت",
        reports_activitylog: "سجل النشاطات للحساب",
        suppliers: "الموردين",
        supplier_management: "دليل الموردين واللوجستيات",
        products_sold: "المنتجات الموردة",
        contact_info: "بيانات الاتصال",
        rating: "التقييم",
        supply_chain: "سلسلة التوريد",
        purchases: "المشتريات",
        purchase_requests: "طلبات الشراء",
        rfqs: "طلبات عروض الأسعار",
        purchase_quotations: "عروض أسعار المشتريات",
        purchase_orders: "أوامر الشراء",
        purchase_invoices: "فواتير الشراء",
        purchase_returns: "مرتجعات المشتريات",
        debit_notes: "إشعارات مدينة",
        supplier_payments: "مدفوعات الموردين",
        payroll: "المرتبات",
        contracts: "العقود",
        salary_register: "مسير الرواتب",
        salary_slips: "قسائم الرواتب",
        salary_advances: "السلف",
        salary_items: "بنود الراتب",
        salary_templates: "قوالب الراتب",
        commissions: "العمولات",
        salesperson: "مندوب المبيعات",
        commission_rate: "نسبة العمولة",
        performance_bonus: "مكافأة الأداء",
        salary_slips_subtitle: "تفاصيل كشوف المرتبات الشهرية وإيصالات الرواتب",
        search_slips_placeholder: "بحث بالموظف أو الشهر...",
        no_salary_slips_found: "لم يتم إنشاء قسائم مرتبات بعد. قم بإنشائها من السجل.",
        salary_slip_breakdown: "تفصيل قسيمة الراتب",
        payroll_receipt: "إيصال راتب",
        receipt_id_label: "رقم الإيصال",
        print_slip_label: "طباعة القسيمة",
        employee_information: "بيانات الموظف",
        permanent_staff: "موظف دائم",
        days_served_label: "أيام العمل",
        salary_summary: "ملخص الراتب",
        net_payable_label: "صافي المستحق",
        payment_breakdown: "تفاصيل الدفع",
        item_description_label: "وصف البند",
        addition_label: "إضافة",
        deduction_label: "خصم",
        transportation_allowance: "بدل انتقال",
        social_insurance: "تأمين اجتماعي",
        vat_label: "ضريبة القيمة المضافة (مستقطعة)",
        loans_advances_repayment: "سداد سلف / قروض",
        fine_penalties_label: "غرامات / جزاءات",
        total_net_payable: "إجمالي صافي المستحق",
        finance_manager_signature: "توقيع مدير الشؤون المالية",
        certified_digital_payroll: "مستند رواتب رقمي معتمد",
        salary_advances_subtitle: "إدارة طلبات سلف الموظفين وجداول السداد",
        search_advances_placeholder: "البحث في السلف...",
        request_advance: "طلب سلفة",
        repayment_starts: "بدء السداد",
        syncing_advances: "جاري مزامنة سجلات السلف...",
        no_advance_requests_found: "لم يتم العثور على طلبات سلف.",
        amount_greater_than_zero_error: "يجب أن يكون المبلغ أكبر من 0",
        save_advance_failed: "فشل في حفظ طلب السلفة.",
        update_status_failed: "فشل في تحديث الحالة.",
        edit_advance_record: "تعديل سجل السلفة",
        new_advance_request: "طلب سلفة جديد",
        advance_amount_egp: "مبلغ السلفة (جنيه)",
        purpose_of_advance_placeholder: "الغرض من السلفة...",
        advance_hint_text: "سيؤدي ذلك إلى تحديث مسير الرواتب والموافقة على القرض. سيتم خصم المدفوعات من راتب الموظف بدءاً من تاريخ بدء السداد.",
        egp: "جنيه",
        close_label: "إغلاق",
        na_label: "غير متاح",
        confirm_delete_record: "حذف السجل؟",
        paid_status: "مدفوع",
        approved: "معتمد",
        rejected: "مرفوض",
        enter_item_name_error: "يرجى إدخال اسم البند",
        save_item_failed: "فشل في حفظ البند.",
        search_items_placeholder: "البحث في البنود...",
        no_salary_items_found: "لم يتم تعريف أي بنود راتب. قم بإنشاء أول إضافة أو خصم.",
        confirm_delete_item: "حذف البند؟",
        addition: "إضافة",
        deduction: "خصم",
        recurring: "متكرر",
        edit_salary_item: "تعديل بند الراتب",
        create_salary_item: "إنشاء بند راتب",
        item_name_payroll_placeholder: "مثال: تأمين صحي، انتقالات، ضريبة 14%",
        value_type_label: "نوع القيمة",
        fixed_amount_egp: "مبلغ ثابت (جنيه)",
        percentage_label: "نسبة مئوية (%)",
        recurring_every_month: "متكرر كل شهر",
        salary_templates_subtitle: "كشوف وتقارير رواتب شهرية قابلة للتصدير",
        total_base_payroll: "إجمالي الرواتب الأساسية",
        monthly_payroll_sheet: "مسير الرواتب الشهري",
        organization_payroll_report: "تقرير رواتب المؤسسة",
        filter_by_name_placeholder: "تصفية بالاسم...",
        generating_report: "جاري إنشاء التقرير...",
        no_payroll_data_month: "لا توجد بيانات رواتب لهذا الشهر.",
        unknown: "غير معروف",
        totals: "الإجماليات",
        prepared_by: "أعده",
        approved_by: "اعتمد من قبل",
        days: "الأيام",
        staff_label: "موظف",
        save_failed: "فشل في حفظ البيانات.",
        delete_confirm: "هل أنت متأكد من حذف هذا؟",
        priority: "الأولوية",
        low: "منخفض",
        medium: "متوسط",
        high: "عالي",
        items_count: "أصناف",
        unique_items: "أصناف فريدة",
        requested_items: "الأصناف المطلوبة",
        add_item: "إضافة صنف",
        qty: "الكمية",
        estimated_price: "السعر التقديري",
        loading_data: "جاري تحميل البيانات...",
        no_data: "لا توجد بيانات متاحة.",

        // Purchasing & Suppliers Extension (Arabic)
        purchase_requests_title: "طلبات الشراء",
        purchase_requests_subtitle: "مسودة وتقديم طلبات المواد أو الأدوات المكتبية أو الخدمات.",
        new_request: "طلب جديد",
        active_requests: "الطلبات النشطة",
        request_title: "عنوان الطلب",
        loading_requests: "جاري تحميل الطلبات...",
        no_purchase_requests_yet: "لا توجد طلبات شراء بعد.",
        no_description: "لا يوجد وصف",
        purchase_orders_title: "أوامر الشراء",
        purchase_orders_subtitle: "إدارة طلبات الموردين، طلبات المخزون، والمصاريف",
        create_order: "إنشاء أمر شراء",
        total_sourced_value: "إجمالي قيمة التوريد",
        lifetime_orders_desc: "أوامر الشراء المتتبعة كلياً",
        order_history: "سجل الأوامر",
        search_orders: "بحث في الأوامر...",
        order_ref: "مرجع الأمر",
        order_number_label: "رقم الأمر",
        date_logged: "تاريخ التسجيل",
        classification: "التصنيف",
        order_details: "تفاصيل الأمر",
        order_reference: "مرجع أمر الشراء",
        link_approved_quotation: "ربط عرض سعر معتمد",
        independent_order: "أمر شراء مستقل",
        order_classification: "تصنيف الأمر",
        standard_items: "أصناف قياسية",
        inventory_stock: "مخزون مستودع",
        standard_quotation: "عرض سعر قياسي",
        bulk_wholesale: "كميات كبيرة / جملة",
        urgent_request: "طلب عاجل",
        financial_status: "الوضع المالي والحالة",
        total_expected_amount: "إجمالي المبلغ المتوقع (جنيه)",
        current_status: "الحالة الحالية",
        sent_processing: "مرسل / قيد التنفيذ",
        completed_paid: "مكتمل / مدفوع",
        documentation_notes: "التوثيق والملاحظات",
        invoice_receipt_url: "ضع رابط الفاتورة/الإيصال هنا...",
        additional_details: "تفاصيل إضافية...",
        auto_expense_hint: "★ وضع الحالة كمكتمل سيقوم بتسجيلها تلقائياً في المصاريف.",
        purchase_quotations_title: "عروض أسعار الشراء",
        purchase_quotations_subtitle: "مراجعة واعتماد عروض أسعار الموردين النهائية.",
        add_quote: "إضافة عرض سعر",
        winning_bid: "العرض الفائز",
        bid_amount: "إجمالي قيمة العرض",
        approve_quote_confirm: "اعتماد هذا العرض؟ سيؤدي ذلك لرفض العروض الأخرى لنفس طلب التسعير.",
        quote_approved_success: "تم اعتماد عرض السعر بنجاح!",
        no_purchase_quotations_found: "لم يتم العثور على عروض أسعار",
        enter_supplier_quotes_desc: "أدخل عروض أسعار الموردين لطلبات التسعير الخاصة بك لبدء عملية المقارنة.",
        enter_supplier_quotation: "إدخال عرض سعر مورد",
        linked_rfq: "طلب التسعير المرتبط",
        select_supplier: "اختر المورد",
        select_supplier_placeholder: "اختر المورد...",
        independent_quote: "عرض سعر مستقل",
        quote_date: "تاريخ العرض",
        rfqs_title: "طلبات عروض الأسعار (RFQ)",
        rfqs_subtitle: "إنشاء وإدارة طلبات عروض الأسعار لمقارنة عدة موردين.",
        new_rfq: "طلب تسعير جديد",
        active_rfqs: "الطلبات التسعير النشطة",
        rfq_title: "عنوان طلب التسعير",
        rfq_details: "تفاصيل طلب التسعير",
        closing_date: "تاريخ الإغلاق",
        vendor_selection: "اختيار الموردين",
        no_rfqs_found: "لم يتم العثور على طلبات تسعير",
        create_rfq_desc: "أنشئ طلباً للحصول على عروض أسعار تنافسية من البائعين.",
        new_rfq_modal_title: "إنشاء طلب تسعير جديد",
        rfq_reference: "مرجع طلب التسعير",
        view_quotes: "عرض العروض",
        approve: "اعتماد",
        reject: "رفض",
        general_quote: "عرض سعر عام",
        rfq_description_desc: "قارن الأسعار من عدة موردين لطلبات الشراء الخاصة بك.",
        no_active_rfqs: "لا توجد طلبات تسعير نشطة",
        active_rfqs_desc: "أنشئ طلب تسعير للبدء في تلقي ومقارنة عروض أسعار الموردين.",
        create_rfq_modal_title: "إنشاء طلب عروض أسعار (RFQ)",
        rfq_title_subject: "عنوان / موضوع طلب التسعير",
        rfq_title_placeholder: "مثال: شراء إسمنت بالكمية الربع الثاني",
        linked_purchase_request: "طلب شراء مرتبط (اختياري)",
        independent_rfq: "طلب تسعير مستقل",
        deadline_for_bids: "الموعد النهائي للعروض",
        select_suppliers_to_invite: "اختر الموردين لدعوتهم",
        no_suppliers_in_directory: "لم يتم العثور على موردين في الدليل.",
        suppliers_count: "موردين",
        purchase_invoices_title: "فواتير الشراء",
        purchase_invoices_subtitle: "إدارة الفواتير والمدفوعات لطلبات الشراء الخاصة بك.",
        add_invoice: "إضافة فاتورة",
        invoice_no: "رقم الفاتورة",
        po_ref: "مرجع طلب الشراء",
        no_purchase_invoices_yet: "لا توجد فواتير شراء بعد.",
        loading_invoices: "جاري تحميل الفواتير...",
        add_purchase_invoice: "إضافة فاتورة شراء",
        linked_purchase_order: "طلب الشراء المرتبط",
        select_po_placeholder: "اختر طلب الشراء...",
        invoice_number_label: "رقم الفاتورة",
        invoice_date: "تاريخ الفاتورة",
        partially_paid: "مدفوع جزئياً",
        // overdue removed (duplicate)
        unpaid: "غير مدفوع",
        purchase_returns_title: "مرتجع المشتريات",
        purchase_returns_subtitle: "إدارة مرتجعات الأصناف واسترداد الأموال من الموردين.",
        log_return: "تسجيل مرتجع",
        return_history: "سجل المرتجعات",
        return_date: "تاريخ المرتجع",
        refund_amount: "مبلغ الاسترداد",
        no_purchase_returns_logged: "لم يتم تسجيل أي مرتجع مشتريات.",
        loading_returns: "جاري تحميل المرتجعات...",
        log_purchase_return: "تسجيل مرتجع مشتريات",
        linked_invoice_optional: "فاتورة مرتبطة (اختياري)",
        independent_return: "مرتجع مستقل",
        reason_for_return: "سبب المرتجع",
        purchase_return_logged_alert: "تم تسجيل مرتجع المشتريات. يجب التحقق من تسويات المخزون يدوياً.",
        supplier_directory_title: "دليل الموردين",
        supplier_directory_subtitle: "إدارة شركاء الخدمات اللوجستية ومصادر المنتجات الخاصة بك.",
        add_supplier: "إضافة مورد",
        logistics_partners: "شركاء الخدمات اللوجستية",
        search_suppliers: "البحث عن موردين...",
        supplier_name_label: "اسم المورد",
        contact_person: "مسؤول الاتصال",
        linked_products: "المنتجات المرتبطة",
        no_suppliers_found_desc: "لم يتم العثور على موردين. أضف شريكك اللوجستي الأول.",
        edit_supplier: "تعديل بيانات المورد",
        add_new_supplier: "إضافة مورد جديد",
        supplier_company_name: "اسم شركة المورد",
        supplier_name_placeholder: "مثال: الفطيم للخدمات اللوجستية",
        full_name_placeholder: "الاسم الكامل",
        phone_number_label: "رقم الهاتف",
        email_address_label: "البريد الإلكتروني",
        address_warehouse: "العنوان / المستودع",
        no_address: "لا يوجد عنوان",
        no_linked_products: "لا توجد منتجات مرتبطة",
        supplier_payments_title: "مدفوعات الموردين",
        supplier_payments_subtitle: "تسوية الفواتير وتتبع الأموال اللوجستية الخارجة.",
        process_payment: "إجراء عملية دفع",
        payment_history: "سجل المدفوعات",
        reference: "المرجع",
        method: "الطريقة",
        no_payment_records_found: "لم يتم العثور على سجلات دفع.",
        loading_payments: "جاري تحميل المدفوعات...",
        process_supplier_payment: "إجراء دفع للمورد",
        select_logistics_partner: "اختر شريكاً لوجستياً...",
        payment_amount_egp: "مبلغ الدفع (جنية مصري)",
        payment_method: "طريقة الدفع",
        bank_transfer: "تحويل بنكي",
        cash: "نقداً",
        cheque: "شيك",
        stash_funds: "أموال الخزينة",
        reference_receipt_no: "رقم المرجع / الإيصال",
        payment_description: "وصف الدفع",
        delete_payment_confirm: "هل تريد حذف سجل الدفع هذا؟ ملاحظة: المصروف المرتبط سيستمر.",
        debit_notes_title: "إشعارات الخصم والتقسيط",
        debit_notes_subtitle: "إدارة التزامات الموردين طويلة الأجل وجداول الدفع.",
        new_debit_note: "إشعار خصم جديد",
        total_liability: "إجمالي الالتزامات",
        active_status: "نشط",
        payment_progress: "تقدم الدفع",
        no_active_debit_notes: "لا توجد إشعارات خصم نشطة",
        no_debit_notes_desc: "لم تقم بإضافة أي التزامات للموردين أو جداول دفع بعد.",
        new_supplier_liability: "التزام مورد جديد (إشعار خصم)",
        number_of_payments: "عدد الدفعات",
        first_payment_date: "تاريخ الدفعة الأولى",
        liability_description: "وصف الالتزام",
        liability_description_placeholder: "مثال: شراء 100 وحدة بالائتمان...",
        debit_note_created_alert: "تم إنشاء إشعار الخصم. تم جدولة الدفعات المستقبلية.",
        no_description_provided: "لم يتم تقديم وصف",
        installments_sync_msg: "ستظهر الدفعات هنا بمجرد مزامنتها.",
        labor_cost: "توزيع تكلفة العمالة",
        paid: "مدفوع",
        pending: "قيد الانتظار",
        draft: "مسودة",

        // Services additions
        services_module: "الخدمات",
        services_subtitle: "إدارة التسويق والخدمات الاستشارية",
        add_service: "إضافة خدمة",
        service_categorization: "تصنيف الخدمة",
        pricing_option: "خيار التسعير",
        fixed_invoice: "فاتورة ثابتة",
        recurring_setup: "إعداد متكرر",
        target_platforms: "المنصات المستهدفة",
        associated_providers: "مزودي الخدمات / الأدوات",
        other: "أخرى",

        // Specific Expenses
        transportation: "مواصلات",
        parking: "ركن سيارة",
        meeting: "اجتماع",
        coffee: "قهوة",
        lunch: "غداء",
        travel: "سفر",

        // Invoices custom items
        custom_item: "عنصر مخصص",
        add_custom_item: "إضافة عنصر مخصص",

        // New Expenses keys
        add_expense: "إضافة مصروف",
        variable_costs: "تكاليف متغيرة",
        sum_utilities: "مجموع فواتير المرافق",
        total_assets: "إجمالي الاستثمار في الأصول",
        operating_expenses: "مصاريف التشغيل",
        amount_egp: "المبلغ (جنية مصري)",
        expense_category: "الفئة",
        expense_type: "النوع",
        expense_description: "الوصف",
        expense_date: "التاريخ",
        assigned_project: "المشروع المرتبط",
        assigned_unit: "الوحدة المرتبطة",
        assigned_branch: "الفرع / الموقع المرتبط",
        upload_receipt: "رفع الفاتورة / الإيصال",
        syncing_ledger: "جاري المزامنة مع الدفتر...",
        no_expenses: "لم يتم تسجيل أي مصاريف حتى الآن.",

        // New Invoice Keys
        total_invoiced: "إجمالي الفواتير",
        all_time_sales: "حجم مبيعات طوال الوقت",
        total_collected: "إجمالي المحصل",
        paid_cleared: "الفواتير المدفوعة",
        pending_amount: "المبلغ المعلق",
        awaiting_payment: "في انتظار دفع العميل",
        drafts: "المسودات",
        invoices: "فواتير",
        work_in_progress: "عمل قيد التقدم",
        syncing_invoices: "جاري مزامنة الفواتير...",
        customer: "العميل",
        select_customer: "اختر العميل",
        linked_project: "المشروع المرتبط",
        boq_details: "تفاصيل البناء وجدول الكميات (اختياري)",
        boq_reference: "مرجع جدول الكميات (من المخزن)",
        no_boq_link: "لا يوجد رابط جدول كميات",
        work_description: "وصف العمل",
        work_description_placeholder: "تفاصيل محددة للعمل/المواد",
        quantity: "الكمية",
        unit_price: "سعر الوحدة",
        vat_percentage: "القيمة المضافة (%)",
        retention_percentage: "الاستقطاع (%)",
        payment_terms: "شروط الدفع",
        payment_terms_placeholder: "مثال: صافي ٣٠ يوم، دفعة مقدمة ٥٠٪",
        final_total_amount: "المبلغ الإجمالي النهائي (جنية مصري)",

        // Forms and Modals generic
        select_category: "اختر الفئة",
        none_general: "بدون / عام",
        none_service: "بدون / خدمة فقط",
        hq_unassigned: "المركز الرئيسي / غير محدد",

        // Sidebar & Navigation
        task_board: "لوحة المهام",
        staff_modules: "وحدات الموظفين",
        core_modules: "الوحدات الأساسية",
        human_resources: "الموارد البشرية",
        purchasing_logistics: "المشتريات واللوجستيات",
        financials_reports: "المالية والتقارير",
        payroll_engine: "محرك الرواتب",
        payroll_engine_desc: "إدارة تعويضات الموظفين، العقود، والسجلات.",
        review_requests: "مراجعة الطلبات",
        loans_dashboard: "لوحة القروض",
        clients: "العملاء",
        purchasing_cycle: "دورة المشتريات",
        purchasing_cycle_desc: "إدارة التوريد، الأوامر، ومرتجعات المشتريات.",
        suppliers_logistics: "الموردين واللوجستيات",
        suppliers_logistics_desc: "إدارة علاقات الموردين، المدفوعات، والأدلة.",
        employees_directory: "دليل الموظفين",
        cashflow_forecast: "توقعات التدفق النقدي",
        staff_member: "عضو فريق",
        plan_platinum: "بلاتيني",
        plan_label: "خطة",
        sales_invoices: "فواتير المبيعات",
        client_quotations: "عروض أسعار العملاء",

        // Dashboard
        launch_wizard: "بدء المساعد",
        interactive_setup_wizard: "مساعد الإعداد التفاعلي",
        team_members_kpi: "أعضاء الفريق",
        listed_services: "الخدمات المدرجة",
        active_loans_debt: "دفعات القروض النشطة",
        active_loans_debt_desc: "إجمالي ديون القروض النشطة المستحقة حالياً",
        loans_manage_desc: "إدارة حالة الدفع والأرصدة وتتبع الربط من خلال وحدة الخزنة.",
        team_member_added: "تم إضافة عضو فريق",
        no_activity: "لم يتم رصد أي نشاط مؤخراً.",
        wizard_desc: "هل أنت جديد في النظام؟ ابدأ رحلتك التعليمية التفاعلية لتوجيهك خلال إنشاء فريقك، وإعداد مشروعك الأول، وتكوين أمورك المالية.",

        // Inventory
        add_material: "إضافة مادة",
        material_stock: "مخزون المواد",
        actions: "الإجراءات",
        in_stock: "متوفر",
        low_stock: "مخزون منخفض",
        out_of_stock: "نفذت الكمية",
        linked_project_label: "المشروع المرتبط",
        none_general_material: "بدون / مادة عامة",
        add_inventory_item: "إضافة صنف للمخزون",
        item_name_placeholder: "مثال: أسمنت",
        item_code_placeholder: "مثال: MAT-001",
        syncing_inventory: "جاري مزامنة المخزون...",

        // Expenses
        assigned_service_item: "الخدمة / البند المرتبط",
        general_service_cost: "تكلفة خدمة عامة",
        general: "عام",
        fixed: "ثابت",
        variable: "متغير",
        asset: "أصل",
        receipt_photo_optional: "صورة الإيصال (اختياري)",
        file_attached: "تم إرفاق ملف",
        provider: "المزود",
        select_provider: "اختر المزود",
        expense_description_placeholder: "أدخل التفاصيل...",
        variable_costs_desc: "تكاليف متغيرة",
        operating_expenses_desc: "مصاريف تشغيلية",

        // Staff
        employee: "موظف",
        add_penalty: "إضافة جزاء",
        add_vacation: "إضافة إجازة",
        pay_salary: "دفع راتب",
        full_time: "دوام كامل",
        daily: "يومي",
        day_label: "يوم",
        mo_label: "شهر",
        days_unit: "أيام",
        employment_type: "نوع التوظيف",
        role_label: "الدور",
        daily_rate_label: "الأجر اليومي",
        team_members_payroll: "أعضاء الفريق والرواتب",
        select_avatar: "اختر شخصية (مرحة / احترافية)",
        hire_date_label: "تاريخ البدء / التعيين",
        employee_saved_success: "تم حفظ الموظف بنجاح.",
        add_staff_failed: "فشل في إضافة الموظف: ",
        pay_salary_success: "تم إنشاء صرف الراتب بنجاح في المصاريف.",
        pay_salary_failed: "فشل في صرف الراتب.",
        penalty_added_success: "تم إضافة الجزاء بنجاح.",
        penalty_failed: "فشل في إضافة الجزاء.",
        vacation_recorded_success: "تم تسجيل الإجازة بنجاح.",
        vacation_recorded_failed: "فشل في تسجيل الإجازة.",
        process_salary: "معالجة الراتب",
        employment_type_label: "نوع التوظيف",
        rate_label: "السعر",
        final_salary_invoice: "فاتورة الراتب النهائية",
        penalty_amount_egp: "مبلغ الجزاء (جنيه)",
        reason_label: "السبب",
        penalty_hint: "سيتم خصم هذا المبلغ تلقائياً من دفعة الراتب القادمة.",
        record_vacation: "تسجيل إجازة",
        start_date_label: "تاريخ البدء",
        end_date_label: "تاريخ الانتهاء",
        total_vacation_days: "إجمالي أيام الإجازة",
        reason_notes: "السبب / ملاحظات",
        vacation_placeholder: "مثال: إجازة سنوية، مناسبة عائلية",
        penalty_placeholder: "مثال: التأخر عن العمل، سوء سلوك",
        days_worked: "الأيام المشتغلة",
        salary_register_title: "مسير الرواتب",
        salary_register_subtitle: "تتبع المدفوعات وإدارة الأرصدة",
        search_staff_month: "ابحث عن موظف أو شهر...",
        period_label: "الفترة",
        record_payment: "تسجيل دفعة",
        generate_update_slip: "إنشاء/تحديث قسيمة",
        syncing_register: "جاري مزامنة السجل...",
        no_salary_records_found: "لم يتم العثور على سجلات رواتب تطابق بحثك.",
        total_outstanding: "إجمالي المستحقات",
        full_amount: "المبلغ بالكامل",
        payment_process_hint: "سيقوم هذا بتحديث مسير الرواتب وإنشاء سجل مطابق في وحدة المصاريف.",
        partial_payment_note: " سيتم تسجيل هذا كدفعة جزيئية.",
        full_settlement_note: " سيتم تسجيل هذا كتسوية كاملة.",
        employee_contracts_title: "عقود الموظفين",
        employee_contracts_subtitle: "توثيق المهام، شروط الراتب وإدارة الخدمات",
        search_contracts: "بحث في العقود...",
        create_contract: "إنشاء عقد",
        no_contracts_found: "لم يتم العثور على عقود. ابدأ بإنشاء واحد!",
        unknown_staff: "موظف غير معروف",
        managing_label: "يدير:",
        base_label: "الأساسي:",
        inc_label: "زيادة",
        starts_label: "يبدأ:",
        ends_label: "ينتهي:",
        new_employment_contract: "عقد توظيف جديد",
        select_staff: "اختر الموظف",
        primary_tasks: "المهام الأساسية / المسؤوليات",
        tasks_placeholder: "الواجبات الأساسية والمخرجات المتوقعة...",
        base_salary_egp: "الراتب الشهري الأساسي (جنيه)",
        yearly_increase_label: "الزيادة السنوية (%)",
        managed_service_optional: "الخدمة المدارة (اختياري)",
        no_service_responsibility: "لا توجد مسؤولية خدمة",
        end_date_optional: "تاريخ الانتهاء (اختياري)",
        contract_saved_success: "تم حفظ العقد بنجاح.",
        contract_save_failed: "فشل في حفظ العقد.",
        contractor: "مقاول",
        salary_paid_success_expense: "تمت معالجة الدفعة وتسجيلها في المصاريف.",
        salary_payment_error: "خطأ في الدفع:",
        salary_payment_failed: "فشل في معالجة الدفعة.",
        no_active_contract_alert: "لم يتم العثور على عقد نشط لهذا الموظف. يرجى إنشاء عقد أولاً.",
        salary_slip_generated_success: "تم إنشاء قسيمة الراتب وتحديث صافي الراتب بنجاح!",
        salary_slip_generate_failed: "فشل في إنشاء قسيمة الراتب.",

        // Settings Extension
        configure_erp_desc: "تكوين بيئة ERP وتفضيلاتك",
        language_interface_desc: "تغيير لغة الواجهة (ثنائية اللغة إنجليزي/عربي)",
        english_us: "الإنجليزية (English)",
        arabic_eg: "العربية (Arabic)",
        user_profile: "ملف المستخدم",
        manage_profile_desc: "إدارة معلوماتك الشخصية وصورتك الرمزية",
        company_name_dashboard: "اسم الشركة (عنوان لوحة التحكم)",
        company_name_placeholder: "مثال: شركة أعمالي المحدودة",
        profile_picture_url: "رابط الصورة الشخصية",
        profile_picture_desc: "يرجى تقديم رابط صورة صالح لصورتك الرمزية.",
        save_profile: "حفظ الملف الشخصي",
        branches_storage_title: "فروع الشركة والمستودعات",
        branches_storage_desc: "إدارة المواقع الفعلية للمصاريف والفواتير",
        add_branch: "إضافة فرع",
        loading_branches: "جاري تحميل الفروع...",
        no_branches_defined: "لم يتم تحديد أي فروع أو مستودعات بعد.",
        edit_branch: "تعديل الفرع",
        no_address_provided: "لم يتم تقديم عنوان",
        subscription_tier_title: "فئة الاشتراك",
        subscription_tier_desc: "افتح الميزات المميزة وزد حدود المستخدمين.",
        silver_plan: "الخطة الفضية",
        gold_plan: "الخطة الذهبية",
        platinum_plan: "الخطة البلاتينية",
        per_mo: "جنية /شهرياً",
        or_per_yr: "أو 30,000 جنية /سنوياً",
        current_plan: "الخطة الحالية",
        included: "مشمول",
        select_silver: "اختر الفضية",
        upgrade_to_gold: "الترقية للذهبية",
        upgrade_to_platinum: "الترقية للبلاتينية",
        danger_zone: "منطقة الخطر",
        destructive_actions_desc: "إجراءات تدميرية وتسجيل الخروج",
        sign_out: "تسجيل الخروج",
        sign_out_desc: "إنهاء جلستك الحالية بأمان.",
        delete_account: "حذف الحساب",
        delete_account_desc: "حذف المستخدم نهائياً. لا يمكن التراجع عن هذا الإجراء.",
        delete_confirm_placeholder: "اكتب DELETE",
        delete_button: "حذف",
        branch_location_name: "اسم الفرع / الموقع",
        branch_location_placeholder: "مثال: المقر الرئيسي، مكتب وسط المدينة...",
        address_details: "العنوان / التفاصيل",
        address_placeholder: "العنوان الفعلي أو معلومات الاتصال...",

        // Expenses Extension
        rent_invoice: "فاتورة إيجار",
        maintenance_invoice: "فاتورة صيانة",
        internet_invoice: "فاتورة إنترنت",
        electricity_invoice: "فاتورة كهرباء",
        water_invoice: "فاتورة مياه",
        phone_mobile_invoice: "فاتورة هاتف / محمول",
        tax: "ضريبة",
        insurance: "تأمين",
        government_utilities: "مرافق حكومية (الحي)",
        office_supplies: "أدوات مكتبية",
        custom_expense_placeholder: "أدخل فئة مصروف مخصصة...",
        internet_provider: "مزود الإنترنت",
        we_telecom_egypt: "وي (المصرية للاتصالات)",
        vodafone_egypt: "فودافون مصر",
        orange_egypt: "أورانج مصر",
        etisalat_misr: "اتصالات مصر",
        nour_adsl: "نور ADSL",

        // Staff Extension
        consultant: "استشاري",
        active: "نشط",
        edit_employee: "تعديل موظف",
        employee_name: "اسم الموظف",
        email_placeholder: "email@company.com",
        role_placeholder: "مثال: مدير مبيعات",
        part_time: "دوام جزئي",
        temporary: "مؤقت",

        // Quotations
        new_quotation: "عرض سعر جديد",
        quotations_subtitle: "إدارة المقترحات وعقود الخدمات المتكررة",
        search_quotes: "بحث في العروض...",
        proposal: "المقترح",
        client_account: "العميل / الحساب",
        valid_until: "صالح حتى",
        syncing_proposals: "جاري مزامنة المقترحات...",
        no_client_quotations_found: "لم يتم العثور على عروض أسعار. ابدأ بإنشاء واحد!",
        mark_accepted: "تحديد كمقبول",
        one_time: "مرة واحدة",
        proposal_name: "العنوان / اسم المقترح",
        select_client: "اختر العميل",
        choose_client: "-- اختر العميل --",
        related_project: "المشروع / الحساب المرتبط",
        optional_account: "-- حساب اختياري --",
        quoted_amount: "المبلغ المعروض",
        recurring_billing: "الفواتير المتكررة",
        cycle: "الدورة",
        terms: "الشروط",
        brief_description: "وصف موجز / النطاق",
        scope_placeholder: "حدد الخدمات المدرجة...",
        new_client_quotation: "عرض سعر عميل جديد",

        // Loans
        loan_management: "إدارة القروض",
        loans_subtitle: "تتبع القروض والسلف الداخلية والخارجية",
        issue_loan: "إصدار قرض",
        outstanding_balance: "الرصيد المستحق",
        active_accounts: "الحسابات النشطة",
        loan_accounts: "حسابات القروض",
        search_loans: "بحث في القروض...",
        borrower: "المقترض",
        principal: "أصل المبلغ",
        remaining_balance: "الرصيد المتبقي",
        loading_loans: "جاري تحميل بيانات القروض...",
        paid_off: "مسدد بالكامل",
        defaulted: "متعثر",
        update_loan_account: "تحديث حساب القرض",
        issue_new_loan: "إصدار قرض جديد",
        borrower_name: "اسم المقترض",
        principal_amount: "أصل مبلغ القرض",
        term_limit: "مدة القرض (بالأشهر)",
        loan_progress: "تقدم القرض",
        total_paid_back: "إجمالي المبلغ المدفوع",
        linking_stash_hint: "قم بتحديث هذا عند ربط التدفقات النقدية من الخزنة بهذا القرض.",

        // Settings Existing (Moved)
        personal_name: "الاسم الشخصي",
        company_name: "اسم الشركة",
        update_profile: "تحديث الملف الشخصي",
        update_company: "تحديث بيانات الشركة",
        profile_picture: "الصورة الشخصية",
        organization_logo: "شعار المنظمة",
        confirm_delete_supplier: "حذف المورد؟",
        add_inventory_item_failed: "فشل في إضافة صنف للمخزون.",
        salary_payment_desc: "صرف راتب لـ",
        pmt_label: "دفعة",
        debit_note_prefix: "إشعار خصم #",
        days_worked_colon: "أيام العمل:",
        supplier_payment_desc_prefix: "دفع للمورد:",
        confirm_delete_material: "حذف المادة؟",

        rtl: "true"
    }
};

type LanguageContextType = {
    language: Language;
    t: (key: string) => string;
    toggleLanguage: () => void;
    isRTL: boolean;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
    const [language, setLanguage] = useState<Language>('en');

    const toggleLanguage = () => {
        setLanguage(prev => (prev === 'en' ? 'ar' : 'en'));
    };

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    const isRTL = language === 'ar';

    useEffect(() => {
        document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
        document.documentElement.lang = language;
    }, [language, isRTL]);

    return (
        <LanguageContext.Provider value={{ language, t, toggleLanguage, isRTL }}>
            <div dir={isRTL ? 'rtl' : 'ltr'}>
                {children}
            </div>
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used within LanguageProvider');
    return context;
};
