"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

type Translations = {
    [key in Language]: {
        [key: string]: string;
    };
};

const translations: Translations = {
    en: {
        dashboard: "Dashboard",
        sales: "Sales",
        rentals: "Rentals",
        staff: "Staff",
        reports: "Reports",
        settings: "Settings",
        welcome: "Welcome back",
        search_placeholder: "Search anything...",
        total_revenue: "Total Revenue",
        active_units: "Active Units",
        pending_invoices: "Pending Invoices",
        revenue_overview: "Revenue Overview",
        recent_activity: "Recent Activity",
        add_unit: "Add Unit",
        create_invoice: "Create Invoice",
        add_employee: "Add Employee",
        units_title: "Property Inventory",
        units_subtitle: "Manage your units and rental assets",
        invoices_title: "Invoices & Billing",
        invoices_subtitle: "Manage transactional history and drafts",
        staff_title: "Staff & HR Operations",
        staff_subtitle: "Manage employees, shifts, and attendance",
        quick_actions: "Quick Actions",
        analysis: "Analysis",
        language: "Language",
        view_details: "View Details",
        price_label: "Price / Month",
        type_label: "Type",
        filter: "Filter",
        apt_1: "Apartment 1 (شقة 1)",
        apt_2: "Apartment 2",
        office_suite: "Office Suite A",
        storage_unit: "Storage Unit 04",
        type_residential: "Residential",
        type_commercial: "Commercial",
        type_industrial: "Industrial",
        export_csv: "Export to CSV",
        upload_doc: "Upload Doc",
        add_photo: "Add Photo",
        assigned: "Assigned",
        team_members: "Team Members",
        latest_transactions: "Latest Transactions",
        branch: "Branch",
        shift: "Shift",
        inventory: "Inventory",
        inventory_subtitle: "Track materials, stock, and cost prices",
        item_name: "Item Name",
        item_code: "Code",
        stock: "Stock",
        cost_price: "Cost Price",
        item_desc: "Description",
        expenses: "Expenses",
        expenses_subtitle: "Fixed costs, utilities, and assets",
        utilities: "Utilities",
        assets: "Assets",
        salary_net: "Net Salary",
        salary_base: "Base Salary",
        penalties: "Penalties",
        vacations: "Vacations",
        installments: "Installments",
        consumer_name: "Consumer Name",
        total_price: "Total Price",
        paid_amount: "Paid Amount",
        remaining: "Remaining",
        projects: "Projects",
        projects_subtitle: "Group and analyze units by construction project",
        add_project: "Add Project",
        project_name: "Project Name",
        total_units: "Total Units",
        project_analytics: "Project Analytics",
        unassigned: "Unassigned",
        select_project: "Select Project",
        price_per_meter: "Price per Meter",
        rooms: "Rooms",
        finished: "Finished",
        unfinished: "Unfinished",
        facilities: "Facilities",
        property_photos: "Property Photos",
        payment_plans: "Payment Plans",
        plan_name: "Plan Name",
        interest_rate: "Interest Rate (%)",
        down_payment: "Down Payment",
        installments_count: "Installments Count",
        overdue: "Overdue",
        collected: "Collected",
        due_this_month: "Due this Month",
        stash: "Stash",
        stash_subtitle: "Manage manual cash inflows and capital deposits",
        add_cash_in: "Add Cash In",
        add_cash_out: "Add Cash Out",
        cash_source: "Source",
        cash_amount: "Amount",
        cash_type: "Type",
        total_receivable: "Total Receivable",
        cheques: "Cheques",
        cheque_management: "Cheque Management",
        inward: "Inward",
        outward: "Outward",
        due_date: "Due Date",
        maturity_date: "Maturity",
        entity: "Entity",
        purpose: "Purpose",
        total_expenses: "Total Expenses",
        net_profit: "Net Profit",
        cash_flow: "Cash Flow",
        financial_forecast: "Financial Forecast",
        operational_costs: "Operational Costs",
        sales_revenue: "Sales Revenue",
        reports_manufacturing: "Manufacturing Reports",
        reports_sms: "SMS Reports",
        reports_points: "Points & Balances",
        reports_memberships: "Memberships Reports",
        reports_workflow: "Workflow Reports",
        reports_timetracking: "Time Tracking",
        reports_activitylog: "Account Activity Log",
        suppliers: "Suppliers",
        supplier_management: "Supplier Directory & Logistics",
        products_sold: "Sold Products",
        contact_info: "Contact Details",
        rating: "Rating",
        supply_chain: "Supply Chain",
        purchases: "Purchases",
        purchase_requests: "Purchase Requests",
        rfqs: "Request for Quotations",
        purchase_quotations: "Purchase Quotations",
        purchase_orders: "Purchase Orders",
        purchase_invoices: "Purchase Invoices",
        purchase_returns: "Purchase Returns",
        debit_notes: "Debit Notes",
        supplier_payments: "Supplier Payments",
        payroll: "Payroll",
        contracts: "Contracts",
        salary_register: "Salary Register",
        salary_slips: "Salary Slips",
        salary_advances: "Salary Advances",
        salary_items: "Salary Items",
        salary_templates: "Salary Templates",
        commissions: "Commissions",
        salesperson: "Salesperson",
        commission_rate: "Commission Rate",
        performance_bonus: "Performance Bonus",
        // Sidebar & Navigation
        task_board: "Task Board",
        staff_modules: "Staff Modules",
        core_modules: "Core Modules",
        human_resources: "Human Resources",
        purchasing_logistics: "Purchasing & Logistics",
        financials_reports: "Financials & Reports",
        payroll_engine: "Payroll engine",
        loans_dashboard: "Loans Dashboard",
        clients: "Clients",
        purchasing_cycle: "Purchasing Cycle",
        employees_directory: "Employees Directory",
        cashflow_forecast: "Cashflow Forecast",
        staff_member: "Staff Member",
        plan_platinum: "Platinum",
        plan_label: "Plan",
        sales_invoices: "Sales Invoices",
        client_quotations: "Client Quotations",

        // Dashboard
        launch_wizard: "Launch Wizard",
        interactive_setup_wizard: "Interactive Setup Wizard",
        team_members_kpi: "Team Members",
        listed_services: "Listed Services",
        active_loans_debt: "Active Loans Debt",
        service_listed: "Service listed",
        team_member_added: "Team Member added",
        no_activity: "No recent activity detected.",
        wizard_desc: "New to the system? Launch our interactive step-by-step pipeline to guide you through creating your team, setting up your first project, and configuring your finances.",

        // Inventory
        add_material: "Add Material",
        material_stock: "Material Stock",
        actions: "Actions",
        in_stock: "In Stock",
        low_stock: "Low Stock",
        out_of_stock: "Out of Stock",
        linked_project_label: "Linked Project",
        none_general_material: "None / General Material",
        add_inventory_item: "Add Inventory Item",
        item_name_placeholder: "e.g. Cement",
        item_code_placeholder: "e.g. MAT-001",
        syncing_inventory: "Syncing inventory...",

        // Expenses
        assigned_service_item: "Assigned Service / Item",
        general_service_cost: "General Service Cost",
        general: "General",
        fixed: "Fixed",
        variable: "Variable",
        asset: "Asset",
        receipt_photo_optional: "Receipt Photo (Optional)",
        file_attached: "File Attached",
        provider: "Provider",
        select_provider: "Select Provider",
        expense_description_placeholder: "Enter details...",
        select_category: "Select Category",
        variable_costs_desc: "Variable Costs",
        operating_expenses_desc: "Operating Expenses",

        // Staff
        employee: "Employee",
        add_penalty: "Add Penalty",
        add_vacation: "Add Vacation",
        pay_salary: "Pay Salary",
        full_time: "Full Time",
        daily: "Daily",
        day_label: "day",
        mo_label: "mo",
        days_unit: "Days",
        employment_type: "Employment Type",
        role_label: "Role",
        daily_rate_label: "Daily Rate",
        team_members_payroll: "Team Members & Payroll",
        select_avatar: "Select Avatar (Funny / Professional)",
        hire_date_label: "Start Date / Hire Date",

        // Settings Extension
        configure_erp_desc: "Configure your ERP environment and preferences",
        language_interface_desc: "Change the interface language (Bilingual EN/AR)",
        english_us: "English (US)",
        arabic_eg: "العربية (Arabic)",
        user_profile: "User Profile",
        manage_profile_desc: "Manage your personal information and avatar",
        company_name_dashboard: "Company Name (Dashboard Title)",
        company_name_placeholder: "e.g. My Business Ltd",
        profile_picture_url: "Profile Picture URL",
        profile_picture_desc: "Provide a valid image URL for your avatar.",
        save_profile: "Save Profile",
        branches_storage_title: "Company Branches & Storage",
        branches_storage_desc: "Manage physical locations for expenses and invoices",
        add_branch: "Add Branch",
        loading_branches: "Loading branches...",
        no_branches_defined: "No branches or storage locations defined yet.",
        edit_branch: "Edit Branch",
        no_address_provided: "No address provided",
        subscription_tier_title: "Subscription Tier",
        subscription_tier_desc: "Unlock premium features and increase your user limits.",
        silver_plan: "Silver Plan",
        gold_plan: "Gold Plan",
        platinum_plan: "Platinum Plan",
        per_mo: "EGP /mo",
        or_per_yr: "or 30,000 EGP /yr",
        current_plan: "Current Plan",
        included: "Included",
        select_silver: "Select Silver",
        upgrade_to_gold: "Upgrade to Gold",
        upgrade_to_platinum: "Upgrade to Platinum",
        danger_zone: "Danger Zone",
        destructive_actions_desc: "Destructive actions and account logouts",
        sign_out: "Sign Out",
        sign_out_desc: "End your current session securely.",
        delete_account: "Delete Account",
        delete_account_desc: "Permanently remove your user. This cannot be undone.",
        delete_confirm_placeholder: "Type DELETE",
        delete_button: "Delete",
        branch_location_name: "Branch / Location Name",
        branch_location_placeholder: "e.g. Headquarters, Downtown Office...",
        address_details: "Address / Details",
        address_placeholder: "Physical address or contact info...",

        // Expenses Extension
        rent_invoice: "Rent Invoice",
        maintenance_invoice: "Maintenance Invoice",
        internet_invoice: "Internet Invoice",
        electricity_invoice: "Electricity Invoice",
        water_invoice: "Water Invoice",
        phone_mobile_invoice: "Phone / Mobile Invoice",
        tax: "Tax",
        insurance: "Insurance",
        government_utilities: "Government utilities (الحي)",
        office_supplies: "Office Supplies",
        custom_expense_placeholder: "Enter custom expense category...",
        internet_provider: "Internet Provider",
        we_telecom_egypt: "WE (Telecom Egypt)",
        vodafone_egypt: "Vodafone Egypt",
        orange_egypt: "Orange Egypt",
        etisalat_misr: "Etisalat Misr",
        nour_adsl: "Nour ADSL",

        // Staff Extension
        consultant: "Consultant",
        active: "Active",
        edit_employee: "Edit Employee",
        employee_name: "Employee Name",
        email_placeholder: "email@company.com",
        role_placeholder: "e.g. Sales Manager",
        part_time: "Part Time",
        temporary: "Temporary",

        // Settings
        personal_name: "Personal Name",
        company_name: "Company Name",
        update_profile: "Update Profile",
        update_company: "Update Company",
        profile_picture: "Profile Picture",
        organization_logo: "Organization Logo",

        rtl: "false"
    },
    ar: {
        dashboard: "لوحة التحكم",
        sales: "المبيعات",
        rentals: "الإيجارات",
        staff: "الموظفين",
        reports: "التقارير",
        settings: "الإعدادات",
        welcome: "مرحباً بك مجدداً",
        search_placeholder: "ابحث عن أي شيء...",
        total_revenue: "إجمالي الإيرادات",
        active_units: "الوحدات النشطة",
        pending_invoices: "الفواتير المعلقة",
        revenue_overview: "نظرة عامة على الإيرادات",
        recent_activity: "النشاط الأخير",
        add_unit: "إضافة وحدة",
        create_invoice: "إنشاء فاتورة",
        add_employee: "إضافة موظف",
        units_title: "مخزون العقارات",
        units_subtitle: "إدارة الوحدات والأصول الإيجارية",
        invoices_title: "الفواتير والفوترة",
        invoices_subtitle: "إدارة السجل المعاملاتي والمسودات",
        staff_title: "الموظفين وعمليات الموارد البشرية",
        staff_subtitle: "إدارة الموظفين، المناوبات، والحضور",
        quick_actions: "إجراءات سريعة",
        analysis: "التحليل",
        language: "اللغة",
        view_details: "عرض التفاصيل",
        price_label: "السعر / شهر",
        type_label: "النوع",
        filter: "تصفية",
        apt_1: "شقة 1 (Apartment 1)",
        apt_2: "شقة 2",
        office_suite: "جناح مكاتب أ",
        storage_unit: "وحدة تخزين 04",
        type_residential: "سكني",
        type_commercial: "تجاري",
        type_industrial: "صناعي",
        export_csv: "تصدير إلى CSV",
        upload_doc: "رفع مستند",
        add_photo: "إضافة صورة",
        assigned: "تم تعيينهم",
        team_members: "أعضاء الفريق",
        latest_transactions: "أحدث المعاملات",
        branch: "الفرع",
        shift: "المناوبة",
        inventory: "المخزون",
        inventory_subtitle: "تتبع المواد، المخزون، وأسعار التكلفة",
        item_name: "اسم الصنف",
        item_code: "الكود",
        stock: "المخزون",
        cost_price: "سعر التكلفة",
        item_desc: "الوصف",
        expenses: "المصاريف",
        expenses_subtitle: "التكاليف الثابتة، المرافق، والأصول",
        utilities: "المرافق",
        assets: "الأصول",
        salary_net: "صافي الراتب",
        salary_base: "الراتب الأساسي",
        penalties: "الجزاءات",
        vacations: "الإجازات",
        installments: "الأقساط",
        consumer_name: "اسم المستهلك",
        total_price: "السعر الإجمالي",
        paid_amount: "المبلغ المدفوع",
        remaining: "المتبقي",
        projects: "المشاريع",
        projects_subtitle: "تجميع وتحليل الوحدات حسب مشروع البناء",
        add_project: "إضافة مشروع",
        project_name: "اسم المشروع",
        total_units: "إجمالي الوحدات",
        project_analytics: "تحليلات المشروع",
        unassigned: "غير محدد",
        select_project: "اختر المشروع",
        price_per_meter: "سعر المتر",
        rooms: "الغرف",
        finished: "مشطب",
        unfinished: "بدون تشطيب",
        facilities: "المرافق",
        property_photos: "صور العقار",
        payment_plans: "خطط الدفع",
        plan_name: "اسم الخطة",
        interest_rate: "نسبة الفائدة (%)",
        down_payment: "الدفعة المقدمة",
        installments_count: "عدد الأقساط",
        overdue: "متأخر",
        collected: "محصل",
        due_this_month: "مستحق هذا الشهر",
        stash: "الخزنة",
        stash_subtitle: "إدارة التدفقات النقدية اليدوية وتدفقات رأس المال",
        add_cash_in: "إضافة نقد وارد",
        add_cash_out: "إضافة نقد صادر",
        cash_source: "المصدر",
        cash_amount: "المبلغ",
        cash_type: "النوع",
        total_receivable: "إجمالي المستحقات",
        cheques: "الشيكات",
        cheque_management: "إدارة الشيكات",
        inward: "وارد",
        outward: "صادر",
        due_date: "تاريخ الاستحقاق",
        maturity_date: "الاستحقاق",
        entity: "الجهة",
        purpose: "الغرض",
        total_expenses: "إجمالي المصروفات",
        net_profit: "صافي الربح",
        cash_flow: "التدفق النقدي",
        financial_forecast: "التوقعات المالية",
        operational_costs: "التكاليف التشغيلية",
        sales_revenue: "إيرادات المبيعات",
        reports_manufacturing: "تقارير التصنيع",
        reports_sms: "تقارير الـ SMS",
        reports_points: "تقارير النقاط و الأرصدة",
        reports_memberships: "تقارير العضويات",
        reports_workflow: "تقارير دورة العمل",
        reports_timetracking: "تقارير تتبع الوقت",
        reports_activitylog: "سجل النشاطات للحساب",
        suppliers: "الموردين",
        supplier_management: "دليل الموردين واللوجستيات",
        products_sold: "المنتجات الموردة",
        contact_info: "بيانات الاتصال",
        rating: "التقييم",
        supply_chain: "سلسلة التوريد",
        purchases: "المشتريات",
        purchase_requests: "طلبات الشراء",
        rfqs: "طلبات عروض الأسعار",
        purchase_quotations: "عروض أسعار المشتريات",
        purchase_orders: "أوامر الشراء",
        purchase_invoices: "فواتير الشراء",
        purchase_returns: "مرتجعات المشتريات",
        debit_notes: "إشعارات مدينة",
        supplier_payments: "مدفوعات الموردين",
        payroll: "المرتبات",
        contracts: "العقود",
        salary_register: "مسير الرواتب",
        salary_slips: "قسائم الرواتب",
        salary_advances: "السلف",
        salary_items: "بنود الراتب",
        salary_templates: "قوالب الراتب",
        commissions: "العمولات",
        salesperson: "مندوب المبيعات",
        commission_rate: "نسبة العمولة",
        performance_bonus: "مكافأة الأداء",
        labor_cost: "توزيع تكلفة العمالة",
        paid: "مدفوع",
        pending: "قيد الانتظار",
        draft: "مسودة",

        // Services additions
        services_module: "الخدمات",
        services_subtitle: "إدارة التسويق والخدمات الاستشارية",
        add_service: "إضافة خدمة",
        service_categorization: "تصنيف الخدمة",
        pricing_option: "خيار التسعير",
        fixed_invoice: "فاتورة ثابتة",
        recurring_setup: "إعداد متكرر",
        target_platforms: "المنصات المستهدفة",
        associated_providers: "مزودي الخدمات / الأدوات",
        other: "أخرى",

        // Specific Expenses
        transportation: "مواصلات",
        parking: "ركن سيارة",
        meeting: "اجتماع",
        coffee: "قهوة",
        lunch: "غداء",
        travel: "سفر",

        // Invoices custom items
        custom_item: "عنصر مخصص",
        add_custom_item: "إضافة عنصر مخصص",

        // New Expenses keys
        add_expense: "إضافة مصروف",
        variable_costs: "تكاليف متغيرة",
        sum_utilities: "مجموع فواتير المرافق",
        total_assets: "إجمالي الاستثمار في الأصول",
        operating_expenses: "مصاريف التشغيل",
        amount_egp: "المبلغ (جنية مصري)",
        expense_category: "الفئة",
        expense_type: "النوع",
        expense_description: "الوصف",
        expense_date: "التاريخ",
        assigned_project: "المشروع المرتبط",
        assigned_unit: "الوحدة المرتبطة",
        assigned_branch: "الفرع / الموقع المرتبط",
        upload_receipt: "رفع الفاتورة / الإيصال",
        syncing_ledger: "جاري المزامنة مع الدفتر...",
        no_expenses: "لم يتم تسجيل أي مصاريف حتى الآن.",

        // New Invoice Keys
        total_invoiced: "إجمالي الفواتير",
        all_time_sales: "حجم مبيعات طوال الوقت",
        total_collected: "إجمالي المحصل",
        paid_cleared: "الفواتير المدفوعة",
        pending_amount: "المبلغ المعلق",
        awaiting_payment: "في انتظار دفع العميل",
        drafts: "المسودات",
        invoices: "فواتير",
        work_in_progress: "عمل قيد التقدم",
        syncing_invoices: "جاري مزامنة الفواتير...",
        customer: "العميل",
        select_customer: "اختر العميل",
        linked_project: "المشروع المرتبط",
        boq_details: "تفاصيل البناء وجدول الكميات (اختياري)",
        boq_reference: "مرجع جدول الكميات (من المخزن)",
        no_boq_link: "لا يوجد رابط جدول كميات",
        work_description: "وصف العمل",
        work_description_placeholder: "تفاصيل محددة للعمل/المواد",
        quantity: "الكمية",
        unit_price: "سعر الوحدة",
        vat_percentage: "القيمة المضافة (%)",
        retention_percentage: "الاستقطاع (%)",
        payment_terms: "شروط الدفع",
        payment_terms_placeholder: "مثال: صافي ٣٠ يوم، دفعة مقدمة ٥٠٪",
        final_total_amount: "المبلغ الإجمالي النهائي (جنية مصري)",

        // Forms and Modals generic
        select_category: "اختر الفئة",
        none_general: "بدون / عام",
        none_service: "بدون / خدمة فقط",
        hq_unassigned: "المركز الرئيسي / غير محدد",

        // Sidebar & Navigation
        task_board: "لوحة المهام",
        staff_modules: "وحدات الموظفين",
        core_modules: "الوحدات الأساسية",
        human_resources: "الموارد البشرية",
        purchasing_logistics: "المشتريات واللوجستيات",
        financials_reports: "المالية والتقارير",
        payroll_engine: "محرك الرواتب",
        loans_dashboard: "لوحة القروض",
        clients: "العملاء",
        purchasing_cycle: "دورة المشتريات",
        employees_directory: "دليل الموظفين",
        cashflow_forecast: "توقعات التدفق النقدي",
        staff_member: "عضو فريق",
        plan_platinum: "بلاتيني",
        plan_label: "خطة",
        sales_invoices: "فواتير المبيعات",
        client_quotations: "عروض أسعار العملاء",

        // Dashboard
        launch_wizard: "بدء المساعد",
        interactive_setup_wizard: "مساعد الإعداد التفاعلي",
        team_members_kpi: "أعضاء الفريق",
        listed_services: "الخدمات المدرجة",
        active_loans_debt: "دفعات القروض النشطة",
        service_listed: "خدمة مدرجة",
        team_member_added: "تم إضافة عضو فريق",
        no_activity: "لم يتم رصد أي نشاط مؤخراً.",
        wizard_desc: "هل أنت جديد في النظام؟ ابدأ رحلتك التعليمية التفاعلية لتوجيهك خلال إنشاء فريقك، وإعداد مشروعك الأول، وتكوين أمورك المالية.",

        // Inventory
        add_material: "إضافة مادة",
        material_stock: "مخزون المواد",
        actions: "الإجراءات",
        in_stock: "متوفر",
        low_stock: "مخزون منخفض",
        out_of_stock: "نفذت الكمية",
        linked_project_label: "المشروع المرتبط",
        none_general_material: "بدون / مادة عامة",
        add_inventory_item: "إضافة صنف للمخزون",
        item_name_placeholder: "مثال: أسمنت",
        item_code_placeholder: "مثال: MAT-001",
        syncing_inventory: "جاري مزامنة المخزون...",

        // Expenses
        assigned_service_item: "الخدمة / البند المرتبط",
        general_service_cost: "تكلفة خدمة عامة",
        general: "عام",
        fixed: "ثابت",
        variable: "متغير",
        asset: "أصل",
        receipt_photo_optional: "صورة الإيصال (اختياري)",
        file_attached: "تم إرفاق ملف",
        provider: "المزود",
        select_provider: "اختر المزود",
        expense_description_placeholder: "أدخل التفاصيل...",
        variable_costs_desc: "تكاليف متغيرة",
        operating_expenses_desc: "مصاريف تشغيلية",

        // Staff
        employee: "موظف",
        add_penalty: "إضافة جزاء",
        add_vacation: "إضافة إجازة",
        pay_salary: "دفع راتب",
        full_time: "دوام كامل",
        daily: "يومي",
        day_label: "يوم",
        mo_label: "شهر",
        days_unit: "أيام",
        employment_type: "نوع التوظيف",
        role_label: "الدور",
        daily_rate_label: "الأجر اليومي",
        team_members_payroll: "أعضاء الفريق والرواتب",
        select_avatar: "اختر شخصية (مرحة / احترافية)",
        hire_date_label: "تاريخ البدء / التعيين",

        // Settings Extension
        configure_erp_desc: "تكوين بيئة ERP وتفضيلاتك",
        language_interface_desc: "تغيير لغة الواجهة (ثنائية اللغة إنجليزي/عربي)",
        english_us: "الإنجليزية (English)",
        arabic_eg: "العربية (Arabic)",
        user_profile: "ملف المستخدم",
        manage_profile_desc: "إدارة معلوماتك الشخصية وصورتك الرمزية",
        company_name_dashboard: "اسم الشركة (عنوان لوحة التحكم)",
        company_name_placeholder: "مثال: شركة أعمالي المحدودة",
        profile_picture_url: "رابط الصورة الشخصية",
        profile_picture_desc: "يرجى تقديم رابط صورة صالح لصورتك الرمزية.",
        save_profile: "حفظ الملف الشخصي",
        branches_storage_title: "فروع الشركة والمستودعات",
        branches_storage_desc: "إدارة المواقع الفعلية للمصاريف والفواتير",
        add_branch: "إضافة فرع",
        loading_branches: "جاري تحميل الفروع...",
        no_branches_defined: "لم يتم تحديد أي فروع أو مستودعات بعد.",
        edit_branch: "تعديل الفرع",
        no_address_provided: "لم يتم تقديم عنوان",
        subscription_tier_title: "فئة الاشتراك",
        subscription_tier_desc: "افتح الميزات المميزة وزد حدود المستخدمين.",
        silver_plan: "الخطة الفضية",
        gold_plan: "الخطة الذهبية",
        platinum_plan: "الخطة البلاتينية",
        per_mo: "جنية /شهرياً",
        or_per_yr: "أو 30,000 جنية /سنوياً",
        current_plan: "الخطة الحالية",
        included: "مشمول",
        select_silver: "اختر الفضية",
        upgrade_to_gold: "الترقية للذهبية",
        upgrade_to_platinum: "الترقية للبلاتينية",
        danger_zone: "منطقة الخطر",
        destructive_actions_desc: "إجراءات تدميرية وتسجيل الخروج",
        sign_out: "تسجيل الخروج",
        sign_out_desc: "إنهاء جلستك الحالية بأمان.",
        delete_account: "حذف الحساب",
        delete_account_desc: "حذف المستخدم نهائياً. لا يمكن التراجع عن هذا الإجراء.",
        delete_confirm_placeholder: "اكتب DELETE",
        delete_button: "حذف",
        branch_location_name: "اسم الفرع / الموقع",
        branch_location_placeholder: "مثال: المقر الرئيسي، مكتب وسط المدينة...",
        address_details: "العنوان / التفاصيل",
        address_placeholder: "العنوان الفعلي أو معلومات الاتصال...",

        // Expenses Extension
        rent_invoice: "فاتورة إيجار",
        maintenance_invoice: "فاتورة صيانة",
        internet_invoice: "فاتورة إنترنت",
        electricity_invoice: "فاتورة كهرباء",
        water_invoice: "فاتورة مياه",
        phone_mobile_invoice: "فاتورة هاتف / محمول",
        tax: "ضريبة",
        insurance: "تأمين",
        government_utilities: "مرافق حكومية (الحي)",
        office_supplies: "أدوات مكتبية",
        custom_expense_placeholder: "أدخل فئة مصروف مخصصة...",
        internet_provider: "مزود الإنترنت",
        we_telecom_egypt: "وي (المصرية للاتصالات)",
        vodafone_egypt: "فودافون مصر",
        orange_egypt: "أورانج مصر",
        etisalat_misr: "اتصالات مصر",
        nour_adsl: "نور ADSL",

        // Staff Extension
        consultant: "استشاري",
        active: "نشط",
        edit_employee: "تعديل موظف",
        employee_name: "اسم الموظف",
        email_placeholder: "email@company.com",
        role_placeholder: "مثال: مدير مبيعات",
        part_time: "دوام جزئي",
        temporary: "مؤقت",

        // Settings Existing (Moved)
        personal_name: "الاسم الشخصي",
        company_name: "اسم الشركة",
        update_profile: "تحديث الملف الشخصي",
        update_company: "تحديث بيانات الشركة",
        profile_picture: "الصورة الشخصية",
        organization_logo: "شعار المنظمة",

        rtl: "true"
    }
};

type LanguageContextType = {
    language: Language;
    t: (key: string) => string;
    toggleLanguage: () => void;
    isRTL: boolean;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
    const [language, setLanguage] = useState<Language>('en');

    const toggleLanguage = () => {
        setLanguage(prev => (prev === 'en' ? 'ar' : 'en'));
    };

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    const isRTL = language === 'ar';

    useEffect(() => {
        document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
        document.documentElement.lang = language;
    }, [language, isRTL]);

    return (
        <LanguageContext.Provider value={{ language, t, toggleLanguage, isRTL }}>
            <div dir={isRTL ? 'rtl' : 'ltr'}>
                {children}
            </div>
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used within LanguageProvider');
    return context;
};
