"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

type Translations = {
    [key in Language]: {
        [key: string]: string;
    };
};

const translations: Translations = {
    en: {
        dashboard: "Dashboard",
        sales: "Sales",
        rentals: "Rentals",
        staff: "Staff",
        reports: "Reports",
        settings: "Settings",
        welcome: "Welcome back",
        search_placeholder: "Search anything...",
        total_revenue: "Total Revenue",
        active_units: "Active Units",
        pending_invoices: "Pending Invoices",
        revenue_overview: "Revenue Overview",
        recent_activity: "Recent Activity",
        add_unit: "Add Unit",
        create_invoice: "Create Invoice",
        add_employee: "Add Employee",
        units_title: "Property Inventory",
        units_subtitle: "Manage your units and rental assets",
        invoices_title: "Invoices & Billing",
        invoices_subtitle: "Manage transactional history and drafts",
        staff_title: "Staff & HR Operations",
        staff_subtitle: "Manage employees, shifts, and attendance",
        quick_actions: "Quick Actions",
        analysis: "Analysis",
        language: "Language",
        view_details: "View Details",
        price_label: "Price / Month",
        type_label: "Type",
        filter: "Filter",
        apt_1: "Apartment 1 (شقة 1)",
        apt_2: "Apartment 2",
        office_suite: "Office Suite A",
        storage_unit: "Storage Unit 04",
        type_residential: "Residential",
        type_commercial: "Commercial",
        type_industrial: "Industrial",
        export_csv: "Export to CSV",
        upload_doc: "Upload Doc",
        add_photo: "Add Photo",
        assigned: "Assigned",
        team_members: "Team Members",
        latest_transactions: "Latest Transactions",
        branch: "Branch",
        shift: "Shift",
        inventory: "Inventory",
        inventory_subtitle: "Track materials, stock, and cost prices",
        item_name: "Item Name",
        item_code: "Code",
        stock: "Stock",
        cost_price: "Cost Price",
        item_desc: "Description",
        expenses: "Expenses",
        expenses_subtitle: "Fixed costs, utilities, and assets",
        utilities: "Utilities",
        assets: "Assets",
        salary_net: "Net Salary",
        salary_base: "Base Salary",
        penalties: "Penalties",
        vacations: "Vacations",
        installments: "Installments",
        consumer_name: "Consumer Name",
        total_price: "Total Price",
        paid_amount: "Paid Amount",
        remaining: "Remaining",
        projects: "Projects",
        projects_subtitle: "Group and analyze units by construction project",
        add_project: "Add Project",
        project_name: "Project Name",
        total_units: "Total Units",
        project_analytics: "Project Analytics",
        unassigned: "Unassigned",
        select_project: "Select Project",
        price_per_meter: "Price per Meter",
        rooms: "Rooms",
        finished: "Finished",
        unfinished: "Unfinished",
        facilities: "Facilities",
        property_photos: "Property Photos",
        payment_plans: "Payment Plans",
        plan_name: "Plan Name",
        interest_rate: "Interest Rate (%)",
        down_payment: "Down Payment",
        installments_count: "Installments Count",
        overdue: "Overdue",
        collected: "Collected",
        due_this_month: "Due this Month",
        total_receivable: "Total Receivable",
        cheques: "Cheques",
        cheque_management: "Cheque Management",
        inward: "Inward",
        outward: "Outward",
        due_date: "Due Date",
        maturity_date: "Maturity",
        entity: "Entity",
        purpose: "Purpose",
        total_expenses: "Total Expenses",
        net_profit: "Net Profit",
        cash_flow: "Cash Flow",
        financial_forecast: "Financial Forecast",
        operational_costs: "Operational Costs",
        sales_revenue: "Sales Revenue",
        reports_manufacturing: "Manufacturing Reports",
        reports_sms: "SMS Reports",
        reports_points: "Points & Balances",
        reports_memberships: "Memberships Reports",
        reports_workflow: "Workflow Reports",
        reports_timetracking: "Time Tracking",
        reports_activitylog: "Account Activity Log",
        suppliers: "Suppliers",
        supplier_management: "Supplier Directory & Logistics",
        products_sold: "Sold Products",
        contact_info: "Contact Details",
        rating: "Rating",
        supply_chain: "Supply Chain",
        purchases: "Purchases",
        purchase_requests: "Purchase Requests",
        rfqs: "Request for Quotations",
        purchase_quotations: "Purchase Quotations",
        purchase_orders: "Purchase Orders",
        purchase_invoices: "Purchase Invoices",
        purchase_returns: "Purchase Returns",
        debit_notes: "Debit Notes",
        supplier_payments: "Supplier Payments",
        payroll: "Payroll",
        contracts: "Contracts",
        salary_register: "Salary Register",
        salary_slips: "Salary Slips",
        salary_advances: "Salary Advances",
        salary_items: "Salary Items",
        salary_templates: "Salary Templates",
        commissions: "Commissions",
        salesperson: "Salesperson",
        commission_rate: "Commission Rate",
        performance_bonus: "Performance Bonus",
        labor_cost: "Labor Cost Attribution",
        paid: "Paid",
        pending: "Pending",
        draft: "Draft",
        rtl: "false"
    },
    ar: {
        dashboard: "لوحة التحكم",
        sales: "المبيعات",
        rentals: "الإيجارات",
        staff: "الموظفين",
        reports: "التقارير",
        settings: "الإعدادات",
        welcome: "مرحباً بك مجدداً",
        search_placeholder: "ابحث عن أي شيء...",
        total_revenue: "إجمالي الإيرادات",
        active_units: "الوحدات النشطة",
        pending_invoices: "الفواتير المعلقة",
        revenue_overview: "نظرة عامة على الإيرادات",
        recent_activity: "النشاط الأخير",
        add_unit: "إضافة وحدة",
        create_invoice: "إنشاء فاتورة",
        add_employee: "إضافة موظف",
        units_title: "مخزون العقارات",
        units_subtitle: "إدارة الوحدات والأصول الإيجارية",
        invoices_title: "الفواتير والفوترة",
        invoices_subtitle: "إدارة السجل المعاملاتي والمسودات",
        staff_title: "الموظفين وعمليات الموارد البشرية",
        staff_subtitle: "إدارة الموظفين، المناوبات، والحضور",
        quick_actions: "إجراءات سريعة",
        analysis: "التحليل",
        language: "اللغة",
        view_details: "عرض التفاصيل",
        price_label: "السعر / شهر",
        type_label: "النوع",
        filter: "تصفية",
        apt_1: "شقة 1 (Apartment 1)",
        apt_2: "شقة 2",
        office_suite: "جناح مكاتب أ",
        storage_unit: "وحدة تخزين 04",
        type_residential: "سكني",
        type_commercial: "تجاري",
        type_industrial: "صناعي",
        export_csv: "تصدير إلى CSV",
        upload_doc: "رفع مستند",
        add_photo: "إضافة صورة",
        assigned: "تم تعيينهم",
        team_members: "أعضاء الفريق",
        latest_transactions: "أحدث المعاملات",
        branch: "الفرع",
        shift: "المناوبة",
        inventory: "المخزون",
        inventory_subtitle: "تتبع المواد، المخزون، وأسعار التكلفة",
        item_name: "اسم الصنف",
        item_code: "الكود",
        stock: "المخزون",
        cost_price: "سعر التكلفة",
        item_desc: "الوصف",
        expenses: "المصاريف",
        expenses_subtitle: "التكاليف الثابتة، المرافق، والأصول",
        utilities: "المرافق",
        assets: "الأصول",
        salary_net: "صافي الراتب",
        salary_base: "الراتب الأساسي",
        penalties: "الجزاءات",
        vacations: "الإجازات",
        installments: "الأقساط",
        consumer_name: "اسم المستهلك",
        total_price: "السعر الإجمالي",
        paid_amount: "المبلغ المدفوع",
        remaining: "المتبقي",
        projects: "المشاريع",
        projects_subtitle: "تجميع وتحليل الوحدات حسب مشروع البناء",
        add_project: "إضافة مشروع",
        project_name: "اسم المشروع",
        total_units: "إجمالي الوحدات",
        project_analytics: "تحليلات المشروع",
        unassigned: "غير محدد",
        select_project: "اختر المشروع",
        price_per_meter: "سعر المتر",
        rooms: "الغرف",
        finished: "مشطب",
        unfinished: "بدون تشطيب",
        facilities: "المرافق",
        property_photos: "صور العقار",
        payment_plans: "خطط الدفع",
        plan_name: "اسم الخطة",
        interest_rate: "نسبة الفائدة (%)",
        down_payment: "الدفعة المقدمة",
        installments_count: "عدد الأقساط",
        overdue: "متأخر",
        collected: "محصل",
        due_this_month: "مستحق هذا الشهر",
        total_receivable: "إجمالي المستحقات",
        cheques: "الشيكات",
        cheque_management: "إدارة الشيكات",
        inward: "وارد",
        outward: "صادر",
        due_date: "تاريخ الاستحقاق",
        maturity_date: "الاستحقاق",
        entity: "الجهة",
        purpose: "الغرض",
        total_expenses: "إجمالي المصروفات",
        net_profit: "صافي الربح",
        cash_flow: "التدفق النقدي",
        financial_forecast: "التوقعات المالية",
        operational_costs: "التكاليف التشغيلية",
        sales_revenue: "إيرادات المبيعات",
        reports_manufacturing: "تقارير التصنيع",
        reports_sms: "تقارير الـ SMS",
        reports_points: "تقارير النقاط و الأرصدة",
        reports_memberships: "تقارير العضويات",
        reports_workflow: "تقارير دورة العمل",
        reports_timetracking: "تقارير تتبع الوقت",
        reports_activitylog: "سجل النشاطات للحساب",
        suppliers: "الموردين",
        supplier_management: "دليل الموردين واللوجستيات",
        products_sold: "المنتجات الموردة",
        contact_info: "بيانات الاتصال",
        rating: "التقييم",
        supply_chain: "سلسلة التوريد",
        purchases: "المشتريات",
        purchase_requests: "طلبات الشراء",
        rfqs: "طلبات عروض الأسعار",
        purchase_quotations: "عروض أسعار المشتريات",
        purchase_orders: "أوامر الشراء",
        purchase_invoices: "فواتير الشراء",
        purchase_returns: "مرتجعات المشتريات",
        debit_notes: "إشعارات مدينة",
        supplier_payments: "مدفوعات الموردين",
        payroll: "المرتبات",
        contracts: "العقود",
        salary_register: "مسير الرواتب",
        salary_slips: "قسائم الرواتب",
        salary_advances: "السلف",
        salary_items: "بنود الراتب",
        salary_templates: "قوالب الراتب",
        commissions: "العمولات",
        salesperson: "مسؤول المبيعات",
        commission_rate: "نسبة العمولة",
        performance_bonus: "مكافأة الأداء",
        labor_cost: "تخصيص تكلفة العمالة",
        paid: "مدفوع",
        pending: "معلق",
        draft: "مسودة",
        rtl: "true"
    }
};

type LanguageContextType = {
    language: Language;
    t: (key: string) => string;
    toggleLanguage: () => void;
    isRTL: boolean;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
    const [language, setLanguage] = useState<Language>('en');

    const toggleLanguage = () => {
        setLanguage(prev => (prev === 'en' ? 'ar' : 'en'));
    };

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    const isRTL = language === 'ar';

    useEffect(() => {
        document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
        document.documentElement.lang = language;
    }, [language, isRTL]);

    return (
        <LanguageContext.Provider value={{ language, t, toggleLanguage, isRTL }}>
            <div dir={isRTL ? 'rtl' : 'ltr'}>
                {children}
            </div>
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used within LanguageProvider');
    return context;
};
